! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Utility Data Module File
! 
! Generated by KPP-2.2.4_gc symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : gckpp_Monitor.f90
! Time                 : Wed Jul 13 11:44:30 2016
! Working directory    : /n/home05/msulprizio/GC/FlexChem/Mechanisms/UCX
! Equation file        : gckpp.kpp
! Output root filename : gckpp
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE gckpp_Monitor


  CHARACTER(LEN=15), PARAMETER, DIMENSION(90) :: SPC_NAMES_0 = (/ &
     'MSA            ','LISOPOH        ','PYAC           ', &
     'CO2            ','RR1            ','RR2            ', &
     'RR3            ','RR4            ','RR5            ', &
     'RR6            ','RR7            ','RR8            ', &
     'RR9            ','RR10           ','RR11           ', &
     'RR12           ','RR13           ','RR14           ', &
     'RR15           ','RR16           ','RR17           ', &
     'RR18           ','RR19           ','RR20           ', &
     'RR21           ','RR22           ','RR23           ', &
     'RR24           ','RR25           ','RR26           ', &
     'RR27           ','RR28           ','RR29           ', &
     'RR30           ','RR31           ','RR32           ', &
     'RR33           ','RR34           ','RR35           ', &
     'RR36           ','RR37           ','RR38           ', &
     'RR39           ','RR40           ','RR41           ', &
     'RR42           ','RR43           ','RR44           ', &
     'RR45           ','RR46           ','RR47           ', &
     'RR48           ','RR49           ','RR50           ', &
     'RR51           ','RR52           ','RR53           ', &
     'RR54           ','RR55           ','RR56           ', &
     'RR57           ','RR58           ','RR59           ', &
     'RR60           ','RR61           ','RR62           ', &
     'RR63           ','RR64           ','RR65           ', &
     'RR66           ','RR67           ','RR68           ', &
     'RR69           ','RR70           ','RR71           ', &
     'RR72           ','RR73           ','RR74           ', &
     'RR75           ','RR76           ','RR77           ', &
     'RR78           ','RR79           ','RR80           ', &
     'RR81           ','RR82           ','RR83           ', &
     'RR84           ','RR85           ','RR86           ' /)
  CHARACTER(LEN=15), PARAMETER, DIMENSION(90) :: SPC_NAMES_1 = (/ &
     'RR87           ','RR88           ','RR89           ', &
     'RR90           ','RR91           ','RR92           ', &
     'RR93           ','RR94           ','RR95           ', &
     'RR96           ','RR97           ','RR98           ', &
     'RR99           ','RR100          ','RR101          ', &
     'RR102          ','RR103          ','RR104          ', &
     'RR105          ','RR106          ','RR107          ', &
     'RR108          ','RR109          ','RR110          ', &
     'RR111          ','RR112          ','RR113          ', &
     'RR114          ','RR115          ','RR116          ', &
     'RR117          ','RR118          ','RR119          ', &
     'RR120          ','RR121          ','RR122          ', &
     'RR123          ','RR124          ','RR125          ', &
     'RR126          ','RR127          ','RR128          ', &
     'RR129          ','RR130          ','RR131          ', &
     'RR132          ','RR133          ','RR134          ', &
     'RR135          ','RR136          ','RR137          ', &
     'RR138          ','RR139          ','RR140          ', &
     'RR141          ','RR142          ','RR143          ', &
     'RR144          ','RR145          ','RR146          ', &
     'RR147          ','RR148          ','RR149          ', &
     'RR150          ','RR151          ','RR152          ', &
     'RR153          ','RR154          ','RR155          ', &
     'RR156          ','RR157          ','RR158          ', &
     'RR159          ','RR160          ','RR161          ', &
     'RR162          ','RR163          ','RR164          ', &
     'RR165          ','RR166          ','RR167          ', &
     'RR168          ','RR169          ','RR170          ', &
     'RR171          ','RR172          ','RR173          ', &
     'RR174          ','RR175          ','RR176          ' /)
  CHARACTER(LEN=15), PARAMETER, DIMENSION(90) :: SPC_NAMES_2 = (/ &
     'RR177          ','RR178          ','RR179          ', &
     'RR180          ','RR181          ','RR182          ', &
     'RR183          ','RR184          ','RR185          ', &
     'RR186          ','RR187          ','RR188          ', &
     'RR189          ','RR190          ','RR191          ', &
     'RR192          ','RR193          ','RR194          ', &
     'RR195          ','RR196          ','RR197          ', &
     'RR198          ','RR199          ','RR200          ', &
     'RR201          ','RR202          ','RR203          ', &
     'RR204          ','RR205          ','RR206          ', &
     'RR207          ','RR208          ','RR209          ', &
     'RR210          ','RR211          ','RR212          ', &
     'RR213          ','RR214          ','RR215          ', &
     'RR216          ','RR217          ','RR218          ', &
     'RR219          ','RR220          ','RR221          ', &
     'RR222          ','RR223          ','RR224          ', &
     'RR225          ','RR226          ','RR227          ', &
     'RR228          ','RR229          ','RR230          ', &
     'RR231          ','RR232          ','RR233          ', &
     'RR234          ','RR235          ','RR236          ', &
     'RR237          ','RR238          ','RR239          ', &
     'RR240          ','RR241          ','RR242          ', &
     'RR243          ','RR244          ','RR245          ', &
     'RR246          ','RR247          ','RR248          ', &
     'RR249          ','RR250          ','RR251          ', &
     'RR252          ','RR253          ','RR254          ', &
     'RR255          ','RR256          ','RR257          ', &
     'RR258          ','RR259          ','RR260          ', &
     'RR261          ','RR262          ','RR263          ', &
     'RR264          ','RR265          ','RR266          ' /)
  CHARACTER(LEN=15), PARAMETER, DIMENSION(90) :: SPC_NAMES_3 = (/ &
     'RR267          ','RR268          ','RR269          ', &
     'RR270          ','RR271          ','RR272          ', &
     'RR273          ','RR274          ','RR275          ', &
     'RR276          ','RR277          ','RR278          ', &
     'RR279          ','RR280          ','RR281          ', &
     'RR282          ','RR283          ','RR284          ', &
     'RR285          ','RR286          ','RR287          ', &
     'RR288          ','RR289          ','RR290          ', &
     'RR291          ','RR292          ','RR293          ', &
     'RR294          ','RR295          ','RR296          ', &
     'RR297          ','RR298          ','RR299          ', &
     'RR300          ','RR301          ','RR302          ', &
     'RR303          ','RR304          ','RR305          ', &
     'RR306          ','RR307          ','RR308          ', &
     'RR309          ','RR310          ','RR311          ', &
     'RR312          ','RR313          ','RR314          ', &
     'RR315          ','RR316          ','RR317          ', &
     'RR318          ','RR319          ','RR320          ', &
     'RR321          ','RR322          ','RR323          ', &
     'RR324          ','RR325          ','RR326          ', &
     'RR327          ','RR328          ','RR329          ', &
     'RR330          ','RR331          ','RR332          ', &
     'RR333          ','RR334          ','RR335          ', &
     'RR336          ','RR337          ','RR338          ', &
     'RR339          ','RR340          ','RR341          ', &
     'RR342          ','RR343          ','RR344          ', &
     'RR345          ','RR346          ','RR347          ', &
     'RR348          ','RR349          ','RR350          ', &
     'RR351          ','RR352          ','RR353          ', &
     'RR354          ','RR355          ','RR356          ' /)
  CHARACTER(LEN=15), PARAMETER, DIMENSION(90) :: SPC_NAMES_4 = (/ &
     'RR357          ','RR358          ','RR359          ', &
     'RR360          ','RR361          ','RR362          ', &
     'RR363          ','RR364          ','RR365          ', &
     'RR366          ','RR367          ','RR368          ', &
     'RR369          ','RR370          ','RR371          ', &
     'RR372          ','RR373          ','RR374          ', &
     'RR375          ','RR376          ','RR377          ', &
     'RR378          ','RR379          ','RR380          ', &
     'RR381          ','RR382          ','RR383          ', &
     'RR384          ','RR385          ','RR386          ', &
     'RR387          ','RR388          ','RR389          ', &
     'RR390          ','RR391          ','RR392          ', &
     'RR393          ','RR394          ','RR395          ', &
     'RR396          ','RR397          ','RR398          ', &
     'RR399          ','RR400          ','RR401          ', &
     'RR402          ','RR403          ','RR404          ', &
     'RR405          ','RR406          ','RR407          ', &
     'RR408          ','RR409          ','RR410          ', &
     'RR411          ','RR412          ','RR413          ', &
     'RR414          ','RR415          ','RR416          ', &
     'RR417          ','RR418          ','RR419          ', &
     'RR420          ','RR421          ','RR422          ', &
     'RR423          ','RR424          ','RR425          ', &
     'RR426          ','RR427          ','RR428          ', &
     'RR429          ','RR430          ','RR431          ', &
     'RR432          ','RR433          ','RR434          ', &
     'RR435          ','RR436          ','RR437          ', &
     'RR438          ','RR439          ','RR440          ', &
     'RR441          ','RR442          ','RR443          ', &
     'RR444          ','RR445          ','RR446          ' /)
  CHARACTER(LEN=15), PARAMETER, DIMENSION(90) :: SPC_NAMES_5 = (/ &
     'RR447          ','RR448          ','RR449          ', &
     'RR450          ','RR451          ','RR452          ', &
     'RR453          ','RR454          ','RR455          ', &
     'RR456          ','RR457          ','RR458          ', &
     'RR459          ','RR460          ','RR461          ', &
     'RR462          ','RR463          ','RR464          ', &
     'RR465          ','RR466          ','RR467          ', &
     'RR468          ','RR469          ','RR470          ', &
     'RR471          ','RR472          ','RR473          ', &
     'RR474          ','RR475          ','RR476          ', &
     'RR477          ','RR478          ','RR479          ', &
     'RR480          ','RR481          ','RR482          ', &
     'RR483          ','RR484          ','RR485          ', &
     'RR486          ','RR487          ','RR488          ', &
     'RR489          ','RR490          ','RR491          ', &
     'RR492          ','RR493          ','RR494          ', &
     'RR495          ','RR496          ','RR497          ', &
     'RR498          ','RR499          ','RR500          ', &
     'RR501          ','RR502          ','RR503          ', &
     'RR504          ','RR505          ','RR506          ', &
     'RR507          ','RR508          ','RR509          ', &
     'RR510          ','RR511          ','RR512          ', &
     'RR513          ','RR514          ','RR515          ', &
     'RR516          ','RR517          ','RR518          ', &
     'RR519          ','RR520          ','RR521          ', &
     'RR522          ','RR523          ','RR524          ', &
     'RR525          ','RR526          ','RR527          ', &
     'RR528          ','CH3CCl3        ','IEPOX          ', &
     'PMNN           ','CCl4           ','CFC11          ', &
     'CFC12          ','CFC113         ','CFC114         ' /)
  CHARACTER(LEN=15), PARAMETER, DIMENSION(90) :: SPC_NAMES_6 = (/ &
     'CFC115         ','H1301          ','H2402          ', &
     'PPN            ','BrNO2          ','H1211          ', &
     'N2O            ','OCS            ','ALK4           ', &
     'N              ','PAN            ','MAP            ', &
     'Cl2O2          ','CHBr3          ','CH2Br2         ', &
     'MPN            ','OClO           ','ClNO2          ', &
     'HCFC22         ','HCFC123        ','HCFC141b       ', &
     'HCFC142b       ','C3H8           ','ETP            ', &
     'HNO2           ','RA3P           ','RB3P           ', &
     'DMS            ','CH3Cl          ','CH3Br          ', &
     'ClOO           ','HNO4           ','MAOP           ', &
     'MP             ','BrCl           ','RP             ', &
     'ETHLN          ','PP             ','PRPN           ', &
     'SO4            ','Br2            ','R4P            ', &
     'C2H6           ','IAP            ','ATOOH          ', &
     'RIP            ','VRP            ','DHMOB          ', &
     'MOBA           ','MRP            ','N2O5           ', &
     'INPN           ','ISNP           ','ISOPNB         ', &
     'MACRNO2        ','IEPOXOO        ','MOBAOO         ', &
     'ROH            ','DIBOO          ','PMN            ', &
     'MVKN           ','H              ','BrNO3          ', &
     'ISOP           ','PRPE           ','Cl2            ', &
     'ISNOHOO        ','ISNOOB         ','PROPNN         ', &
     'HOBr           ','A3O2           ','GLYX           ', &
     'MAOPO2         ','CH4            ','GAOO           ', &
     'MVKOO          ','B3O2           ','ACET           ', &
     'CH2OO          ','MACRN          ','MGLYOO         ', &
     'ISOPND         ','MGLOO          ','PO2            ', &
     'CH3CHOO        ','MAN2           ','ISNOOA         ', &
     'PRN1           ','H2O2           ','ETO2           ' /)
  CHARACTER(LEN=15), PARAMETER, DIMENSION(56) :: SPC_NAMES_7 = (/ &
     'VRO2           ','KO2            ','RCO3           ', &
     'HC5OO          ','GLYC           ','MRO2           ', &
     'ClNO3          ','R4N1           ','HOCl           ', &
     'ATO2           ','ISN1           ','HNO3           ', &
     'MAO3           ','INO2           ','RIO2           ', &
     'HC5            ','HAC            ','MGLY           ', &
     'ISOPNBO2       ','ISOPNDO2       ','MACROO         ', &
     'R4O2           ','R4N2           ','BrO            ', &
     'RCHO           ','MEK            ','ClO            ', &
     'MACR           ','ALD2           ','MVK            ', &
     'SO2            ','MCO3           ','CO             ', &
     'HCl            ','Cl             ','O              ', &
     'NO3            ','Br             ','OH             ', &
     'HO2            ','HBr            ','H2O            ', &
     'O3             ','CH2O           ','MO2            ', &
     'O1D            ','NO             ','NO2            ', &
     'ACTA           ','EOH            ','H2             ', &
     'HCOOH          ','MOH            ','N2             ', &
     'O2             ','RCOOH          ' /)
  CHARACTER(LEN=15), PARAMETER, DIMENSION(686) :: SPC_NAMES = (/&
    SPC_NAMES_0, SPC_NAMES_1, SPC_NAMES_2, SPC_NAMES_3, SPC_NAMES_4, &
    SPC_NAMES_5, SPC_NAMES_6, SPC_NAMES_7 /)


  INTEGER, PARAMETER, DIMENSION(360) :: FLUX_MAP_0 = (/ &
       5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, &
      17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, &
      29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, &
      41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, &
      53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, &
      65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, &
      77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, &
      89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99,100, &
     101,102,103,104,105,106,107,108,109,110,111,112, &
     113,114,115,116,117,118,119,120,121,122,123,124, &
     125,126,127,128,129,130,131,132,133,134,135,136, &
     137,138,139,140,141,142,143,144,145,146,147,148, &
     149,150,151,152,153,154,155,156,157,158,159,160, &
     161,162,163,164,165,166,167,168,169,170,171,172, &
     173,174,175,176,177,178,179,180,181,182,183,184, &
     185,186,187,188,189,190,191,192,193,194,195,196, &
     197,198,199,200,201,202,203,204,205,206,207,208, &
     209,210,211,212,213,214,215,216,217,218,219,220, &
     221,222,223,224,225,226,227,228,229,230,231,232, &
     233,234,235,236,237,238,239,240,241,242,243,244, &
     245,246,247,248,249,250,251,252,253,254,255,256, &
     257,258,259,260,261,262,263,264,265,266,267,268, &
     269,270,271,272,273,274,275,276,277,278,279,280, &
     281,282,283,284,285,286,287,288,289,290,291,292, &
     293,294,295,296,297,298,299,300,301,302,303,304, &
     305,306,307,308,309,310,311,312,313,314,315,316, &
     317,318,319,320,321,322,323,324,325,326,327,328, &
     329,330,331,332,333,334,335,336,337,338,339,340, &
     341,342,343,344,345,346,347,348,349,350,351,352, &
     353,354,355,356,357,358,359,360,361,362,363,364 /)
  INTEGER, PARAMETER, DIMENSION(168) :: FLUX_MAP_1 = (/ &
     365,366,367,368,369,370,371,372,373,374,375,376, &
     377,378,379,380,381,382,383,384,385,386,387,388, &
     389,390,391,392,393,394,395,396,397,398,399,400, &
     401,402,403,404,405,406,407,408,409,410,411,412, &
     413,414,415,416,417,418,419,420,421,422,423,424, &
     425,426,427,428,429,430,431,432,433,434,435,436, &
     437,438,439,440,441,442,443,444,445,446,447,448, &
     449,450,451,452,453,454,455,456,457,458,459,460, &
     461,462,463,464,465,466,467,468,469,470,471,472, &
     473,474,475,476,477,478,479,480,481,482,483,484, &
     485,486,487,488,489,490,491,492,493,494,495,496, &
     497,498,499,500,501,502,503,504,505,506,507,508, &
     509,510,511,512,513,514,515,516,517,518,519,520, &
     521,522,523,524,525,526,527,528,529,530,531,532 /)
  INTEGER, PARAMETER, DIMENSION(528) :: FLUX_MAP = (/&
    FLUX_MAP_0, FLUX_MAP_1 /)

  INTEGER, DIMENSION(1) :: LOOKAT
  INTEGER, DIMENSION(1) :: MONITOR
  CHARACTER(LEN=15), DIMENSION(1) :: SMASS
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_0 = (/ &
     '       O3 + NO --> RR1 + NO2 + O2                                                                   ', &
     '       OH + O3 --> RR2 + HO2 + O2                                                                   ', &
     '      HO2 + O3 --> RR3 + OH + 2 O2                                                                  ', &
     '      O3 + NO2 --> RR4 + NO3 + O2                                                                   ', &
     '      O3 + MO2 --> RR5 + HO2 + CH2O + O2                                                            ', &
     '          2 OH --> RR6 + O + H2O                                                                    ', &
     '          2 OH --> RR7 + H2O2                                                                       ', &
     '      OH + HO2 --> RR8 + H2O + O2                                                                   ', &
     '     H2O2 + OH --> RR9 + HO2 + H2O                                                                  ', &
     '      HO2 + NO --> RR10 + OH + NO2                                                                  ', &
     '         2 HO2 --> RR11 + H2O2 + O2                                                                 ', &
     '       CO + OH --> CO2 + RR12 + HO2                                                                 ', &
     '      CH4 + OH --> RR13 + H2O + MO2                                                                 ', &
     '      MO2 + NO --> RR14 + HO2 + CH2O + NO2                                                          ', &
     '     HO2 + MO2 --> RR15 + MP + O2                                                                   ', &
     '         2 MO2 --> RR16 + CH2O + MOH + O2                                                           ', &
     '         2 MO2 --> RR17 + 2 HO2 + 2 CH2O                                                            ', &
     '       MP + OH --> RR18 + H2O + MO2                                                                 ', &
     '       MP + OH --> RR19 + OH + H2O + CH2O                                                           ', &
     '    ATOOH + OH --> RR20 + ATO2 + H2O                                                                ', &
     '    ATOOH + OH --> RR21 + MGLY + OH + H2O                                                           ', &
     '     OH + CH2O --> RR22 + CO + HO2 + H2O                                                            ', &
     '      OH + NO2 --> RR23 + HNO3                                                                      ', &
     '     HNO3 + OH --> RR24 + NO3 + H2O                                                                 ', &
     '       OH + NO --> RR25 + HNO2                                                                      ', &
     '     HNO2 + OH --> RR26 + H2O + NO2                                                                 ', &
     '     HO2 + NO2 --> RR27 + HNO4                                                                      ', &
     '          HNO4 --> RR28 + HO2 + NO2                                                                 ', &
     '     HNO4 + OH --> RR29 + H2O + NO2 + O2                                                            ', &
     '     NO3 + HO2 --> RR30 + OH + NO2 + O2                                                             ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_1 = (/ &
     '      NO3 + NO --> RR31 + 2 NO2                                                                     ', &
     '      NO3 + OH --> RR32 + HO2 + NO2                                                                 ', &
     '     NO3 + NO2 --> RR33 + N2O5                                                                      ', &
     '          N2O5 --> RR34 + NO3 + NO2                                                                 ', &
     '    OH + HCOOH --> CO2 + RR35 + HO2 + H2O                                                           ', &
     '      OH + MOH --> RR36 + HO2 + CH2O                                                                ', &
     '     NO3 + NO2 --> RR37 + NO + NO2 + O2                                                             ', &
     '    NO3 + CH2O --> RR38 + HNO3 + CO + HO2                                                           ', &
     '     ALD2 + OH --> RR39 + 0.95 MCO3 + 0.05 CO + 0.05 HO2 + H2O + 0.05 CH2O ... etc.                 ', &
     '    ALD2 + NO3 --> RR40 + HNO3 + MCO3                                                               ', &
     '    MCO3 + NO2 --> RR41 + PAN                                                                       ', &
     '           PAN --> RR42 + MCO3 + NO2                                                                ', &
     '     MCO3 + NO --> CO2 + RR43 + MO2 + NO2                                                           ', &
     '     C2H6 + OH --> RR44 + ETO2 + H2O                                                                ', &
     '     ETO2 + NO --> RR45 + ALD2 + HO2 + NO2                                                          ', &
     '     C3H8 + OH --> RR46 + B3O2                                                                      ', &
     '     C3H8 + OH --> RR47 + A3O2                                                                      ', &
     '     A3O2 + NO --> RR48 + RCHO + HO2 + NO2                                                          ', &
     '      PO2 + NO --> RR49 + ALD2 + HO2 + CH2O + NO2                                                   ', &
     '     ALK4 + OH --> RR50 + R4O2                                                                      ', &
     '     R4O2 + NO --> RR51 + 0.05 A3O2 + 0.18 B3O2 + 0.32 ACET + 0.32 ETO2 ... etc.                    ', &
     '     R4O2 + NO --> RR52 + R4N2                                                                      ', &
     '     R4N1 + NO --> RR53 + 0.3 R4O2 + 0.57 RCHO + 0.75 ALD2 + 0.39 CH2O ... etc.                     ', &
     '     ATO2 + NO --> RR54 + 0.04 R4N2 + 0.96 MCO3 + 0.96 CH2O + 0.96 NO2 ... etc.                     ', &
     '      KO2 + NO --> RR55 + 0.07 R4N2 + 0.93 ALD2 + 0.93 MCO3 + 0.93 NO2 ... etc.                     ', &
     '     RIO2 + NO --> RR56 + 0.047 ISOPNB + 0.1 DIBOO + 0.07 ISOPND + 0.123 HC5 ... etc.               ', &
     '          RIO2 --> RR57 + 0.5 GLYX + 0.5 GLYC + 0.5 HAC + 0.5 MGLY + OH ... etc.                    ', &
     '     VRO2 + NO --> RR58 + 0.12 MVKN + 0.53 GLYC + 0.35 MGLY + 0.53 MCO3 ... etc.                    ', &
     '     MRO2 + NO --> RR59 + 0.15 MACRN + 0.728 HAC + 0.122 MGLY + 0.728 CO ... etc.                   ', &
     '          MRO2 --> RR60 + HAC + CO + OH                                                             ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_2 = (/ &
     '     MAN2 + NO --> RR61 + 0.5 PROPNN + 0.5 MGLY + 0.5 CO + 0.5 OH + 0.5 CH2O ... etc.               ', &
     '     B3O2 + NO --> RR62 + ACET + HO2 + NO2                                                          ', &
     '     INO2 + NO --> RR63 + 0.7 ISN1 + 0.23 HC5 + 0.035 MACR + 0.035 MVK ... etc.                     ', &
     '    INO2 + NO3 --> RR64 + 0.7 ISN1 + 0.23 HC5 + 0.035 MACR + 0.035 MVK ... etc.                     ', &
     '    ISN1 + NO3 --> RR65 + 0.4 ISNOOB + 0.6 ISNOOA + 0.6 HNO3                                        ', &
     '  ISNOOA + NO3 --> RR66 + R4N2 + CO + HO2 + NO2                                                     ', &
     '   ISNOOA + NO --> RR67 + R4N2 + CO + HO2 + NO2                                                     ', &
     '  ISNOOA + NO2 --> RR68 + PMN                                                                       ', &
     '  ISNOOA + HO2 --> RR69 + 0.75 RP + 0.25 O3 + 0.25 RCOOH                                            ', &
     '  ISNOOB + NO3 --> RR70 + GLYX + R4N2 + 2 NO2                                                       ', &
     '   ISNOOB + NO --> RR71 + 0.94 GLYX + 0.94 R4N2 + 1.88 NO2                                          ', &
     '  ISNOOB + HO2 --> RR72 + INPN                                                                      ', &
     '  ISNOOB + MO2 --> RR73 + 0.7 GLYX + 0.7 R4N2 + 0.5 HO2 + 0.75 CH2O + 0.7 NO2 ... etc.              ', &
     '     ISN1 + O3 --> RR74 + 0.7 GLYX + 0.3 R4N2 + 0.5 HO2 + 0.75 CH2O + 0.7 NO2 ... etc.              ', &
     '     ISN1 + OH --> RR75 + 0.655 ISNOHOO + 0.345 ISNOOA                                              ', &
     '  ISNOHOO + NO --> RR76 + 0.919 GLYX + 0.934 R4N2 + 0.934 HO2                                       ', &
     ' ISNOHOO + HO2 --> RR77 + INPN                                                                      ', &
     ' ISNOHOO + MO2 --> RR78 + 0.7 GLYX + 0.7 R4N2 + 1.2 HO2 + 0.75 CH2O + 0.25 MOH ... etc.             ', &
     '        2 INO2 --> RR79 + 0.5 ISOPND + 1.2 ISN1 + 0.23 HC5 + 0.035 MACR ... etc.                    ', &
     '     PRN1 + NO --> RR80 + ALD2 + CH2O + 2 NO2                                                       ', &
     '    ALK4 + NO3 --> RR81 + HNO3 + R4O2                                                               ', &
     '     R4N2 + OH --> RR82 + R4N1 + H2O                                                                ', &
     '     OH + ACTA --> CO2 + RR83 + H2O + MO2                                                           ', &
     '     RCHO + OH --> RR84 + RCO3 + H2O                                                                ', &
     '    RCO3 + NO2 --> RR85 + PPN                                                                       ', &
     '           PPN --> RR86 + RCO3 + NO2                                                                ', &
     '    MAO3 + NO2 --> RR87 + PMN                                                                       ', &
     '           PMN --> RR88 + MAO3 + NO2                                                                ', &
     '     RCO3 + NO --> RR89 + ETO2 + NO2                                                                ', &
     '     MAO3 + NO --> CO2 + RR90 + 0.5 MCO3 + 0.5 CO + 0.5 CH2O + 0.5 MO2 ... etc.                     ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_3 = (/ &
     '    RCHO + NO3 --> RR91 + RCO3 + HNO3                                                               ', &
     '     ACET + OH --> RR92 + ATO2 + H2O                                                                ', &
     '    A3O2 + MO2 --> RR93 + 0.25 ROH + 0.75 RCHO + HO2 + 0.75 CH2O + 0.25 MOH ... etc.                ', &
     '     PO2 + MO2 --> RR94 + 0.25 ROH + 0.16 HAC + 0.09 RCHO + 0.5 ALD2 + HO2 ... etc.                 ', &
     '    R4O2 + HO2 --> RR95 + R4P                                                                       ', &
     '    R4N1 + HO2 --> RR96 + R4N2                                                                      ', &
     '    ATO2 + HO2 --> RR97 + 0.85 ATOOH + 0.15 MCO3 + 0.15 OH + 0.15 CH2O ... etc.                     ', &
     '     KO2 + HO2 --> RR98 + 0.85 ATOOH + 0.15 ALD2 + 0.15 MCO3 + 0.15 OH ... etc.                     ', &
     '    RIO2 + HO2 --> RR99 + 0.88 RIP + 0.047 MACR + 0.073 MVK + 0.12 OH + 0.12 HO2 ... etc.           ', &
     '    VRO2 + HO2 --> RR100 + 0.1 VRP + 0.578 GLYC + 0.102 MGLY + 0.033 RCHO ... etc.                  ', &
     '    MRO2 + HO2 --> RR101 + MRP                                                                      ', &
     '    MAN2 + HO2 --> RR102 + 0.85 ISNP + 0.075 PROPNN + 0.075 MGLY + 0.075 CO ... etc.                ', &
     '    B3O2 + HO2 --> RR103 + RB3P                                                                     ', &
     '    INO2 + HO2 --> RR104 + INPN                                                                     ', &
     '    PRN1 + HO2 --> RR105 + PRPN                                                                     ', &
     '      MEK + OH --> RR106 + KO2 + H2O                                                                ', &
     '    ETO2 + MO2 --> RR107 + 0.75 ALD2 + HO2 + 0.75 CH2O + 0.25 EOH + 0.25 MOH ... etc.               ', &
     '     MEK + NO3 --> RR108 + KO2 + HNO3                                                               ', &
     '    R4O2 + MO2 --> RR109 + 0.25 ROH + 0.03 A3O2 + 0.09 B3O2 + 0.16 ACET ... etc.                    ', &
     '    R4N1 + MO2 --> RR110 + 0.25 ROH + 0.15 R4O2 + 0.54 RCHO + 0.38 ALD2 ... etc.                    ', &
     '    ATO2 + MO2 --> RR111 + 0.2 HAC + 0.5 MGLY + 0.3 MCO3 + 0.3 HO2 + 0.5 CH2O ... etc.              ', &
     '     KO2 + MO2 --> RR112 + 0.25 ROH + 0.25 MEK + 0.5 ALD2 + 0.5 MCO3 + 0.5 HO2 ... etc.             ', &
     '    RIO2 + MO2 --> RR113 + 0.24 ROH + 0.3 HC5 + 0.18 MACR + 0.28 MVK + 1.1 HO2 ... etc.             ', &
     '        2 RIO2 --> RR114 + 0.48 ROH + 0.5 HC5 + 0.36 MACR + 0.56 MVK + 1.28 HO2 ... etc.            ', &
     '   HC5OO + MO2 --> RR115 + 0.25 ROH + 0.13 GLYC + 0.18 HAC + 0.29 MGLY ... etc.                     ', &
     '    VRO2 + MO2 --> RR116 + 0.25 ROH + 0.36 GLYC + 0.14 MGLY + 0.25 MEK ... etc.                     ', &
     '    MRO2 + MO2 --> RR117 + 0.15 ROH + 0.595 HAC + 0.255 MGLY + 0.595 CO ... etc.                    ', &
     '    MAN2 + MO2 --> RR118 + 0.375 PROPNN + 0.375 MGLY + 0.25 R4N2 + 0.375 CO ... etc.                ', &
     '    B3O2 + MO2 --> RR119 + 0.25 ROH + 0.75 ACET + HO2 + 0.75 CH2O + 0.25 MOH ... etc.               ', &
     '    INO2 + MO2 --> RR120 + 0.25 ISOPND + 0.6 ISN1 + 0.115 HC5 + 0.018 MACR ... etc.                 ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_4 = (/ &
     '    PRN1 + MO2 --> RR121 + 0.25 ROH + 0.25 RCHO + 0.5 ALD2 + 0.5 HO2 + 1.25 CH2O ... etc.           ', &
     '      OH + EOH --> RR122 + ALD2 + HO2                                                               ', &
     '      ROH + OH --> RR123 + RCHO + HO2                                                               ', &
     '        2 ETO2 --> RR124 + 2 ALD2 + 2 HO2                                                           ', &
     '        2 ETO2 --> RR125 + ALD2 + EOH                                                               ', &
     '    ETO2 + HO2 --> RR126 + ETP                                                                      ', &
     '    A3O2 + HO2 --> RR127 + RA3P                                                                     ', &
     '     PO2 + HO2 --> RR128 + PP                                                                       ', &
     '    MCO3 + HO2 --> RR129 + 0.41 MAP + 0.44 OH + 0.15 O3 + 0.44 MO2 + 0.15 ACTA ... etc.             ', &
     '    RCO3 + HO2 --> RR130 + 0.41 RP + 0.44 ETO2 + 0.44 OH + 0.15 O3 + 0.15 RCOOH ... etc.            ', &
     '    MAO3 + HO2 --> RR131 + 0.41 MAOP + 0.39 CO + 0.44 OH + 0.15 O3 + 0.59 CH2O ... etc.             ', &
     '     PRPE + OH --> RR132 + PO2                                                                      ', &
     '     PRPE + O3 --> RR133 + 0.1 CH4 + 0.12 CH2OO + 0.12 CH3CHOO + 0.5 ALD2 ... etc.                  ', &
     '      PMN + OH --> RR134 + HAC + CO + NO2                                                           ', &
     '      PMN + O3 --> RR135 + MCO3 + NO3 + CH2O                                                        ', &
     '     GLYC + OH --> 0.361 CO2 + RR136 + 0.134 GLYX + 0.505 CO + 0.227 OH ... etc.                    ', &
     '     GLYC + OH --> RR137 + CO + OH + HCOOH                                                          ', &
     '    PRPE + NO3 --> RR138 + PRN1                                                                     ', &
     '     GLYX + OH --> RR139 + 2 CO + HO2                                                               ', &
     '     MGLY + OH --> RR140 + MCO3 + CO                                                                ', &
     '    GLYX + NO3 --> RR141 + HNO3 + 2 CO + HO2                                                        ', &
     '    MGLY + NO3 --> RR142 + HNO3 + MCO3 + CO                                                         ', &
     '     ISOP + OH --> LISOPOH + RR143 + RIO2                                                           ', &
     '      MVK + OH --> RR144 + VRO2                                                                     ', &
     '     MACR + OH --> RR145 + 0.47 MRO2 + 0.53 MAO3                                                    ', &
     '      HAC + OH --> RR146 + MGLY + HO2                                                               ', &
     '      HAC + OH --> 0.5 CO2 + RR147 + 0.5 CO + OH + 0.5 MO2 + 0.5 ACTA + 0.5 HCOOH ... etc.          ', &
     '   A3O2 + MCO3 --> RR148 + RCHO + HO2 + MO2                                                         ', &
     '    PO2 + MCO3 --> RR149 + ALD2 + HO2 + CH2O + MO2                                                  ', &
     '   A3O2 + MCO3 --> RR150 + RCHO + ACTA                                                              ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_5 = (/ &
     '    PO2 + MCO3 --> RR151 + 0.65 HAC + 0.35 RCHO + ACTA                                              ', &
     '     ISOP + O3 --> RR152 + 0.128 PRPE + 0.044 MVKOO + 0.12 CH2OO + 0.054 VRO2 ... etc.              ', &
     '      MVK + O3 --> RR153 + 0.12 CH2OO + 0.12 MGLOO + 0.5 MGLY + 0.1 ALD2 ... etc.                   ', &
     '     MACR + O3 --> RR154 + 0.211 CH2OO + 0.022 MGLYOO + 0.88 MGLY + 0.099 MCO3 ... etc.             ', &
     '    ISOP + NO3 --> RR155 + INO2                                                                     ', &
     '    MACR + NO3 --> RR156 + MAN2                                                                     ', &
     '    MACR + NO3 --> RR157 + HNO3 + MAO3                                                              ', &
     '    RCO3 + MO2 --> RR158 + ETO2 + HO2 + CH2O                                                        ', &
     '    MAO3 + MO2 --> RR159 + MCO3 + HO2 + 2 CH2O                                                      ', &
     '    RCO3 + MO2 --> RR160 + CH2O + RCOOH                                                             ', &
     '    MAO3 + MO2 --> RR161 + CH2O + RCOOH                                                             ', &
     '     INPN + OH --> RR162 + MEK + OH + NO2                                                           ', &
     '     INPN + OH --> RR163 + 0.36 INO2 + 0.64 R4N2 + 0.64 OH                                          ', &
     '     PRPN + OH --> RR164 + 0.791 PROPNN + 0.209 PRN1 + 0.791 OH                                     ', &
     '      ETP + OH --> RR165 + 0.36 ETO2 + 0.64 ALD2 + 0.64 OH                                          ', &
     '     RA3P + OH --> RR166 + 0.36 A3O2 + 0.64 RCHO + 0.64 OH                                          ', &
     '     RB3P + OH --> RR167 + 0.209 B3O2 + 0.791 ACET + 0.791 OH                                       ', &
     '      R4P + OH --> RR168 + 0.209 R4O2 + 0.791 RCHO + 0.791 OH                                       ', &
     '       RP + OH --> RR169 + RCO3                                                                     ', &
     '       PP + OH --> RR170 + 0.209 PO2 + 0.791 HAC + 0.791 OH                                         ', &
     '      RIP + OH --> RR171 + 0.387 RIO2 + 0.613 HC5 + 0.613 OH                                        ', &
     '      RIP + OH --> RR172 + IEPOX + OH                                                               ', &
     '    IEPOX + OH --> RR173 + IEPOXOO                                                                  ', &
     ' IEPOXOO + HO2 --> 0.2 CO2 + RR174 + 0.275 GLYX + 0.275 GLYC + 0.725 HAC ... etc.                   ', &
     '  IEPOXOO + NO --> 0.2 CO2 + RR175 + 0.275 GLYX + 0.275 GLYC + 0.725 HAC ... etc.                   ', &
     '      IAP + OH --> RR176 + 0.654 DHMOB + 0.346 HC5OO + 0.654 OH                                     ', &
     '      VRP + OH --> RR177 + 0.209 VRO2 + 0.791 MEK + 0.791 OH                                        ', &
     '      MRP + OH --> RR178 + MRO2                                                                     ', &
     '      MRP + OH --> CO2 + RR179 + HAC + OH                                                           ', &
     '     MAOP + OH --> RR180 + MAO3                                                                     ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_6 = (/ &
     '     MAOP + OH --> RR181 + MAOPO2                                                                   ', &
     ' MAOPO2 + MCO3 --> 2 CO2 + RR182 + HAC + OH + MO2                                                   ', &
     ' MAOPO2 + MCO3 --> RR183 + MEK + ACTA                                                               ', &
     '  MAOPO2 + MO2 --> 0.7 CO2 + RR184 + 0.3 ROH + 0.7 HAC + 0.7 OH + 0.7 HO2 ... etc.                  ', &
     '      2 MAOPO2 --> 2 CO2 + RR185 + 2 HAC + 2 OH                                                     ', &
     '  MAOPO2 + HO2 --> CO2 + RR186 + HAC + 2 OH                                                         ', &
     '   MAOPO2 + NO --> CO2 + RR187 + HAC + OH + NO2                                                     ', &
     '   MAOPO2 + NO --> RR188 + HNO3                                                                     ', &
     '      MAP + OH --> RR189 + MCO3                                                                     ', &
     '    C2H6 + NO3 --> RR190 + ETO2 + HNO3                                                              ', &
     '      HC5 + O3 --> RR191 + 0.055 GAOO + 0.055 MGLYOO + 0.5 GLYC + 0.5 MGLY ... etc.                 ', &
     '        2 MCO3 --> RR192 + 2 MO2                                                                    ', &
     '    MCO3 + MO2 --> RR193 + HO2 + CH2O + MO2                                                         ', &
     '    MCO3 + MO2 --> RR194 + CH2O + ACTA                                                              ', &
     '   R4O2 + MCO3 --> RR195 + 0.05 A3O2 + 0.18 B3O2 + 0.32 ACET + 0.32 ETO2 ... etc.                   ', &
     '   ATO2 + MCO3 --> RR196 + MCO3 + CH2O + MO2                                                        ', &
     '    KO2 + MCO3 --> RR197 + ALD2 + MCO3 + MO2                                                        ', &
     '   RIO2 + MCO3 --> CO2 + RR198 + 0.113 DIBOO + 0.14 HC5 + 0.294 MACR + 0.453 MVK ... etc.           ', &
     '  HC5OO + MCO3 --> RR199 + 0.29 DHMOB + 0.17 MOBA + 0.216 GLYX + 0.234 GLYC ... etc.                ', &
     '   VRO2 + MCO3 --> RR200 + 0.6 GLYC + 0.4 MGLY + 0.6 MCO3 + 0.4 HO2 + 0.4 CH2O ... etc.             ', &
     '   MRO2 + MCO3 --> RR201 + 0.857 HAC + 0.143 MGLY + 0.857 CO + 0.85 HO2 ... etc.                    ', &
     '   B3O2 + MCO3 --> RR202 + ACET + HO2 + MO2                                                         ', &
     '   R4N1 + MCO3 --> RR203 + 0.3 R4O2 + 0.57 RCHO + 0.75 ALD2 + 0.39 CH2O ... etc.                    ', &
     '   MAN2 + MCO3 --> CO2 + RR204 + 0.5 PROPNN + 0.5 MGLY + 0.5 CO + 0.5 HO2 ... etc.                  ', &
     '   INO2 + MCO3 --> RR205 + 0.7 ISN1 + 0.23 HC5 + 0.035 MACR + 0.035 MVK ... etc.                    ', &
     '   PRN1 + MCO3 --> RR206 + ALD2 + CH2O + MO2 + NO2                                                  ', &
     '   R4O2 + MCO3 --> RR207 + MEK + ACTA                                                               ', &
     '   ATO2 + MCO3 --> RR208 + MEK + ACTA                                                               ', &
     '    KO2 + MCO3 --> RR209 + MEK + ACTA                                                               ', &
     '   RIO2 + MCO3 --> RR210 + MEK + ACTA                                                               ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_7 = (/ &
     '  HC5OO + MCO3 --> RR211 + MEK + ACTA                                                               ', &
     '   VRO2 + MCO3 --> RR212 + MEK + ACTA                                                               ', &
     '   MRO2 + MCO3 --> RR213 + MEK + ACTA                                                               ', &
     '   R4N1 + MCO3 --> RR214 + RCHO + NO2 + ACTA                                                        ', &
     '   MAN2 + MCO3 --> RR215 + RCHO + NO2 + ACTA                                                        ', &
     '   INO2 + MCO3 --> RR216 + RCHO + NO2 + ACTA                                                        ', &
     '   PRN1 + MCO3 --> RR217 + RCHO + NO2 + ACTA                                                        ', &
     '   B3O2 + MCO3 --> RR218 + ACET + ACTA                                                              ', &
     '   ETO2 + MCO3 --> RR219 + ALD2 + HO2 + MO2                                                         ', &
     '   ETO2 + MCO3 --> RR220 + ALD2 + ACTA                                                              ', &
     '   RCO3 + MCO3 --> RR221 + ETO2 + MO2                                                               ', &
     '   MAO3 + MCO3 --> RR222 + MCO3 + CH2O + MO2                                                        ', &
     '         2 NO3 --> RR223 + 2 NO2 + O2                                                               ', &
     '     MO2 + NO2 --> RR224 + MPN                                                                      ', &
     '           MPN --> RR225 + MO2 + NO2                                                                ', &
     '   ISOPNB + O3 --> RR226 + 0.61 MVKN + 0.39 MACRN + 0.27 OH + CH2O                                  ', &
     '   ISOPND + O3 --> RR227 + 0.5 ETHLN + 0.5 PROPNN + 0.5 GLYC + 0.5 HAC ... etc.                     ', &
     '           HO2 --> RR228 + O2                                                                       ', &
     '           NO2 --> RR229 + 0.5 HNO2 + 0.5 HNO3                                                      ', &
     '           NO3 --> RR230 + HNO3                                                                     ', &
     '    N2O5 + H2O --> RR231 + 2 HNO3                                                                   ', &
     '      DMS + OH --> RR232 + SO2 + CH2O + MO2                                                         ', &
     '      DMS + OH --> 0.25 MSA + RR233 + 0.75 SO2 + MO2                                                ', &
     '     DMS + NO3 --> RR234 + HNO3 + SO2 + CH2O + MO2                                                  ', &
     '      SO2 + OH --> RR235 + SO4 + HO2                                                                ', &
     '       Br + O3 --> RR236 + BrO + O2                                                                 ', &
     '     BrO + HO2 --> RR237 + HOBr + O2                                                                ', &
     '      Br + HO2 --> RR238 + HBr + O2                                                                 ', &
     '      OH + HBr --> RR239 + Br + H2O                                                                 ', &
     '         2 BrO --> RR240 + 2 Br + O2                                                                ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_8 = (/ &
     '         2 BrO --> RR241 + Br2 + O2                                                                 ', &
     '      BrO + NO --> RR242 + Br + NO2                                                                 ', &
     '    BrNO3 + Br --> RR243 + Br2 + NO3                                                                ', &
     '      Br2 + OH --> RR244 + HOBr + Br                                                                ', &
     '      HOBr + O --> RR245 + BrO + OH                                                                 ', &
     '       O + HBr --> RR246 + Br + OH                                                                  ', &
     '      BrO + OH --> RR247 + Br + HO2                                                                 ', &
     '      NO3 + Br --> RR248 + BrO + NO2                                                                ', &
     '     Br + CH2O --> RR249 + CO + HO2 + HBr                                                           ', &
     '     ALD2 + Br --> RR250 + MCO3 + CO + HBr                                                          ', &
     '     ACET + Br --> RR251 + ATO2 + CO + HBr                                                          ', &
     '     C2H6 + Br --> RR252 + ETO2 + CO + HBr                                                          ', &
     '     C3H8 + Br --> RR253 + A3O2 + CO + HBr                                                          ', &
     '      Br + NO2 --> RR254 + BrNO2                                                                    ', &
     '     BrO + NO2 --> RR255 + BrNO3                                                                    ', &
     '    CHBr3 + OH --> RR256 + 3 Br                                                                     ', &
     '   CH2Br2 + OH --> RR257 + 2 Br                                                                     ', &
     '    CH3Br + OH --> RR258 + Br + HO2 + H2O                                                           ', &
     '   BrNO3 + H2O --> RR259 + HOBr + HNO3                                                              ', &
     '          HOBr --> RR260 + 0.5 Br2 + H2O                                                            ', &
     '           HBr --> RR261 + 0.5 Br2                                                                  ', &
     '          HOBr --> RR262 + 0.5 Br2 + H2O                                                            ', &
     '           HBr --> RR263 + 0.5 Br2                                                                  ', &
     '      HC5 + OH --> RR264 + HC5OO                                                                    ', &
     '    HC5OO + NO --> RR265 + 0.29 DHMOB + 0.17 MOBA + 0.216 GLYX + 0.234 GLYC ... etc.                ', &
     '    HC5OO + NO --> RR266 + HNO3                                                                     ', &
     '   HC5OO + HO2 --> RR267 + 0.1 IAP + 0.9 GLYC + 0.9 MGLY + 0.9 OH + 0.9 HO2 ... etc.                ', &
     '   ISOPND + OH --> RR268 + ISOPNDO2                                                                 ', &
     '   ISOPNB + OH --> RR269 + ISOPNBO2                                                                 ', &
     ' ISOPNDO2 + NO --> RR270 + 0.13 ETHLN + 0.15 PROPNN + 0.07 MACRN + 0.15 GLYC ... etc.               ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_9 = (/ &
     ' ISOPNDO2 + NO --> RR271 + HNO3                                                                     ', &
     'ISOPNDO2 + HO2 --> RR272 + 0.065 ETHLN + 0.5 ISNP + 0.075 PROPNN + 0.035 MACRN ... etc.             ', &
     ' ISOPNBO2 + NO --> RR273 + 0.14 MVKN + 0.26 MACRN + 0.6 GLYC + 0.6 HAC ... etc.                     ', &
     ' ISOPNBO2 + NO --> RR274 + HNO3                                                                     ', &
     'ISOPNBO2 + HO2 --> RR275 + 0.5 ISNP + 0.07 MVKN + 0.13 MACRN + 0.3 GLYC ... etc.                    ', &
     '     ISNP + OH --> RR276 + 0.612 R4N1 + 0.193 ISOPNBO2 + 0.193 ISOPNDO2 ... etc.                    ', &
     '     MVKN + OH --> 0.35 PYAC + RR277 + 0.65 MGLY + NO3 + 0.35 CH2O + 0.65 HCOOH ... etc.            ', &
     '    MACRN + OH --> RR278 + MACRNO2                                                                  ', &
     '  MACRNO2 + NO --> 0.93 CO2 + RR279 + 0.85 HAC + 0.07 MGLY + 0.15 NO3 + 0.08 CH2O ... etc.          ', &
     ' MACRNO2 + HO2 --> 0.93 CO2 + RR280 + 0.85 HAC + 0.07 MGLY + 0.15 NO3 + OH ... etc.                 ', &
     ' MACRNO2 + NO2 --> RR281 + PMNN                                                                     ', &
     '          PMNN --> RR282 + MACRNO2 + NO2                                                            ', &
     '    DHMOB + OH --> RR283 + 0.5 HAC + 0.5 MEK + 1.5 CO + HO2                                         ', &
     '    DIBOO + NO --> RR284 + 0.48 GLYX + 0.52 GLYC + 0.48 HAC + 0.52 MGLY ... etc.                    ', &
     '    DIBOO + NO --> RR285 + HNO3                                                                     ', &
     '   DIBOO + HO2 --> RR286 + 0.85 R4P + 0.072 GLYX + 0.078 GLYC + 0.072 HAC ... etc.                  ', &
     '     MOBA + OH --> RR287 + MOBAOO                                                                   ', &
     '   MOBAOO + NO --> CO2 + RR288 + RCHO + HO2 + NO2                                                   ', &
     '   MOBAOO + NO --> RR289 + HNO3                                                                     ', &
     '  MOBAOO + HO2 --> 0.5 CO2 + RR290 + 0.5 R4P + 0.5 RCHO + 0.5 OH + 0.5 HO2 ... etc.                 ', &
     '     MOBA + O3 --> CO2 + RR291 + MEK + OH + HO2                                                     ', &
     '    ETHLN + OH --> CO2 + RR292 + CH2O + NO2                                                         ', &
     '   PROPNN + OH --> RR293 + MGLY + NO2                                                               ', &
     '    CH2OO + NO --> RR294 + CH2O + NO2                                                               ', &
     '   CH2OO + NO2 --> RR295 + NO3 + CH2O                                                               ', &
     '   CH2OO + SO2 --> RR296 + SO4 + CH2O                                                               ', &
     '   CH2OO + H2O --> RR297 + H2O2 + CH2O                                                              ', &
     '   CH2OO + H2O --> RR298 + HCOOH                                                                    ', &
     '   MACROO + CO --> RR299 + MACR                                                                     ', &
     '   MACROO + NO --> RR300 + MACR + NO2                                                               ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_10 = (/ &
     '  MACROO + NO2 --> RR301 + MACR + NO3                                                               ', &
     '  MACROO + SO2 --> RR302 + SO4 + MACR                                                               ', &
     '  MACROO + H2O --> RR303 + MRP                                                                      ', &
     '  MACROO + H2O --> RR304 + H2O2 + MACR                                                              ', &
     '    MVKOO + CO --> RR305 + MVK                                                                      ', &
     '    MVKOO + NO --> RR306 + MVK + NO2                                                                ', &
     '   MVKOO + NO2 --> RR307 + MVK + NO3                                                                ', &
     '   MVKOO + SO2 --> RR308 + SO4 + MVK                                                                ', &
     '   MVKOO + H2O --> RR309 + H2O2 + MVK                                                               ', &
     '   MGLYOO + CO --> RR310 + MGLY                                                                     ', &
     '   MGLYOO + NO --> RR311 + MGLY + NO2                                                               ', &
     '  MGLYOO + NO2 --> RR312 + MGLY + NO3                                                               ', &
     '  MGLYOO + SO2 --> RR313 + SO4 + MGLY                                                               ', &
     '  MGLYOO + H2O --> RR314 + H2O2 + MGLY                                                              ', &
     '    MGLOO + CO --> RR315 + MGLY                                                                     ', &
     '    MGLOO + NO --> RR316 + MGLY + NO2                                                               ', &
     '   MGLOO + NO2 --> RR317 + MGLY + NO3                                                               ', &
     '   MGLOO + SO2 --> RR318 + SO4 + MGLY                                                               ', &
     '   MGLOO + H2O --> RR319 + MCO3 + MO2                                                               ', &
     '   MGLOO + H2O --> RR320 + H2O2 + MGLY                                                              ', &
     '  CH3CHOO + CO --> RR321 + ALD2                                                                     ', &
     '  CH3CHOO + NO --> RR322 + ALD2 + NO2                                                               ', &
     ' CH3CHOO + NO2 --> RR323 + ALD2 + NO3                                                               ', &
     ' CH3CHOO + SO2 --> RR324 + SO4 + ALD2                                                               ', &
     ' CH3CHOO + H2O --> RR325 + H2O2 + ALD2                                                              ', &
     ' CH3CHOO + H2O --> RR326 + ACTA                                                                     ', &
     '     GAOO + CO --> RR327 + GLYC                                                                     ', &
     '     GAOO + NO --> RR328 + GLYC + NO2                                                               ', &
     '    GAOO + NO2 --> RR329 + GLYC + NO3                                                               ', &
     '    GAOO + SO2 --> RR330 + SO4 + GLYC                                                               ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_11 = (/ &
     '    GAOO + H2O --> RR331 + H2O2 + GLYC                                                              ', &
     '    GAOO + H2O --> RR332 + HAC                                                                      ', &
     '     H2O + O1D --> RR333 + 2 OH                                                                     ', &
     '      O1D + N2 --> RR334 + O + N2                                                                   ', &
     '      O1D + O2 --> RR335 + O + O2                                                                   ', &
     '      O1D + H2 --> RR336 + H + OH                                                                   ', &
     '     N2O + O1D --> RR337 + N2 + O2                                                                  ', &
     '     N2O + O1D --> RR338 + 2 NO                                                                     ', &
     '     CH4 + O1D --> RR339 + OH + MO2                                                                 ', &
     '     CH4 + O1D --> RR340 + CH2O + H2                                                                ', &
     '     CH4 + O1D --> RR341 + H + HO2 + CH2O                                                           ', &
     '        O + O2 --> RR342 + O3                                                                       ', &
     '        O + O3 --> RR343 + 2 O2                                                                     ', &
     '       OH + H2 --> RR344 + H + H2O                                                                  ', &
     '        O + OH --> RR345 + H + O2                                                                   ', &
     '       O + HO2 --> RR346 + OH + O2                                                                  ', &
     '      O3 + O1D --> RR347 + 2 O2                                                                     ', &
     '      O3 + O1D --> RR348 + 2 O + O2                                                                 ', &
     '       OCS + O --> RR349 + SO2 + CO                                                                 ', &
     '      OCS + OH --> CO2 + RR350 + SO2                                                                ', &
     '       O + NO2 --> RR351 + NO + O2                                                                  ', &
     '       O + NO3 --> RR352 + NO2 + O2                                                                 ', &
     '        O + NO --> RR353 + NO2                                                                      ', &
     '       O + NO2 --> RR354 + NO3                                                                      ', &
     '      H2O2 + O --> RR355 + OH + HO2                                                                 ', &
     '        H + O2 --> RR356 + HO2                                                                      ', &
     '        H + O3 --> RR357 + OH + O2                                                                  ', &
     '       H + HO2 --> RR358 + 2 OH                                                                     ', &
     '       H + HO2 --> RR359 + O + H2O                                                                  ', &
     '       H + HO2 --> RR360 + H2 + O2                                                                  ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_12 = (/ &
     '        N + O2 --> RR361 + O + NO                                                                   ', &
     '        N + NO --> RR362 + O + N2                                                                   ', &
     '       N + NO2 --> RR363 + N2O + O                                                                  ', &
     '       BrO + O --> RR364 + Br + O2                                                                  ', &
     '      O + CH2O --> RR365 + CO + OH + HO2                                                            ', &
     '     HCl + O1D --> RR366 + 0.24 H + 0.24 ClO + 0.09 HCl + 0.67 Cl + 0.09 O ... etc.                 ', &
     '     HBr + O1D --> RR367 + 0.15 H + 0.15 BrO + 0.2 O + 0.65 Br + 0.65 OH ... etc.                   ', &
     '     Cl2 + O1D --> RR368 + 0.25 Cl2 + 0.75 ClO + 0.75 Cl + 0.25 O                                   ', &
     '    CCl4 + O1D --> RR369 + 0.14 CCl4 + 0.86 ClO + 2.58 Cl + 0.14 O                                  ', &
     '   CH3Br + O1D --> RR370 + 0.44 BrO + 0.56 Br + MO2                                                 ', &
     '  CH2Br2 + O1D --> RR371 + 0.05 CH2Br2 + 0.95 BrO + 0.05 O + 0.95 Br                                ', &
     '   CHBr3 + O1D --> RR372 + 0.32 CHBr3 + 0.68 BrO + 0.32 O + 1.36 Br                                 ', &
     '  HCFC22 + O1D --> RR373 + 0.28 HCFC22 + 0.55 ClO + 0.17 Cl + 0.28 O                                ', &
     '   CFC11 + O1D --> RR374 + 0.12 CFC11 + 0.88 ClO + 1.76 Cl + 0.12 O                                 ', &
     '   CFC12 + O1D --> RR375 + 0.14 CFC12 + 0.86 ClO + 1.72 Cl + 0.14 O                                 ', &
     '   H1211 + O1D --> RR376 + 0.36 H1211 + 0.31 BrO + 0.33 ClO + 0.31 Cl + 0.36 O ... etc.             ', &
     '   H1301 + O1D --> RR377 + 0.59 H1301 + 0.41 BrO + 0.59 O                                           ', &
     'HCFC141b + O1D --> RR378 + 0.31 HCFC141b + 0.69 ClO + 0.69 Cl + 0.31 O ... etc.                     ', &
     'HCFC142b + O1D --> RR379 + 0.26 HCFC142b + 0.74 ClO + 0.26 O                                        ', &
     ' HCFC123 + O1D --> RR380 + 0.21 HCFC123 + 0.79 ClO + 0.79 Cl + 0.21 O                               ', &
     '  CFC113 + O1D --> RR381 + 0.25 CFC113 + 0.75 ClO + 1.5 Cl + 0.25 O                                 ', &
     '  CFC114 + O1D --> RR382 + 0.25 CFC114 + 0.75 ClO + 0.75 Cl + 0.25 O                                ', &
     '  CFC115 + O1D --> RR383 + 0.7 CFC115 + 0.3 ClO + 0.7 O                                             ', &
     '   H2402 + O1D --> RR384 + 0.25 H2402 + 0.75 BrO + 0.25 O + 0.75 Br                                 ', &
     '      Cl2 + OH --> RR385 + HOCl + Cl                                                                ', &
     '     ClO + MO2 --> RR386 + ClOO + HO2 + CH2O                                                        ', &
     '      ClO + OH --> RR387 + Cl + HO2                                                                 ', &
     '      ClO + OH --> RR388 + HCl + O2                                                                 ', &
     '     OClO + OH --> RR389 + HOCl + O2                                                                ', &
     '    Cl2O2 + OH --> RR390 + ClOO + HOCl                                                              ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_13 = (/ &
     '      HCl + OH --> RR391 + Cl + H2O                                                                 ', &
     '     HOCl + OH --> RR392 + ClO + H2O                                                                ', &
     '    ClNO2 + OH --> RR393 + HOCl + NO2                                                               ', &
     '    ClNO3 + OH --> RR394 + HOCl + NO3                                                               ', &
     '    CH3Cl + OH --> RR395 + Cl + HO2 + H2O                                                           ', &
     '  CH3CCl3 + OH --> RR396 + 3 Cl + H2O                                                               ', &
     '   HCFC22 + OH --> RR397 + Cl + H2O                                                                 ', &
     ' HCFC141b + OH --> RR398 + 2 Cl + H2O                                                               ', &
     ' HCFC142b + OH --> RR399 + Cl + H2O                                                                 ', &
     '  HCFC123 + OH --> RR400 + 2 Cl + H2O                                                               ', &
     '      CH4 + Cl --> RR401 + HCl + MO2                                                                ', &
     '     Cl + CH2O --> RR402 + CO + HCl + HO2                                                           ', &
     '       Cl + O3 --> RR403 + ClO + O2                                                                 ', &
     '       Cl + H2 --> RR404 + H + HCl                                                                  ', &
     '     H2O2 + Cl --> RR405 + HCl + HO2                                                                ', &
     '      Cl + HO2 --> RR406 + HCl + O2                                                                 ', &
     '      Cl + HO2 --> RR407 + ClO + OH                                                                 ', &
     '       ClO + O --> RR408 + Cl + O2                                                                  ', &
     '     ClO + HO2 --> RR409 + HOCl + O2                                                                ', &
     '      ClO + NO --> RR410 + Cl + NO2                                                                 ', &
     '     ClO + NO2 --> RR411 + ClNO3                                                                    ', &
     '         2 ClO --> RR412 + Cl2 + O2                                                                 ', &
     '         2 ClO --> RR413 + ClOO + Cl                                                                ', &
     '         2 ClO --> RR414 + OClO + Cl                                                                ', &
     '       Cl + O2 --> RR415 + ClOO                                                                     ', &
     '          ClOO --> RR416 + Cl + O2                                                                  ', &
     '         2 ClO --> RR417 + Cl2O2                                                                    ', &
     '         Cl2O2 --> RR418 + 2 ClO                                                                    ', &
     '     ClOO + Cl --> RR419 + Cl2 + O2                                                                 ', &
     '     ClOO + Cl --> RR420 + 2 ClO                                                                    ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_14 = (/ &
     '     BrO + ClO --> RR421 + OClO + Br                                                                ', &
     '     BrO + ClO --> RR422 + ClOO + Br                                                                ', &
     '     BrO + ClO --> RR423 + BrCl + O2                                                                ', &
     '     ClNO3 + O --> RR424 + ClO + NO3                                                                ', &
     '    ClNO3 + Cl --> RR425 + Cl2 + NO3                                                                ', &
     '    CH3Cl + Cl --> RR426 + CO + 2 HCl + HO2                                                         ', &
     '    N2O5 + HCl --> RR427 + ClNO2 + HNO3                                                             ', &
     '   ClNO3 + H2O --> RR428 + HOCl + HNO3                                                              ', &
     '   ClNO3 + HCl --> RR429 + Cl2 + HNO3                                                               ', &
     '   ClNO3 + HBr --> RR430 + BrCl + HNO3                                                              ', &
     '   BrNO3 + HCl --> RR431 + BrCl + HNO3                                                              ', &
     '    HOCl + HCl --> RR432 + Cl2 + H2O                                                                ', &
     '    HOCl + HBr --> RR433 + BrCl + H2O                                                               ', &
     '    HOBr + HCl --> RR434 + BrCl + H2O                                                               ', &
     '            O3 --> RR435 + O + O2                                                                   ', &
     '            O3 --> RR436 + O1D + O2                                                                 ', &
     '            O2 --> RR437 + 2 O                                                                      ', &
     '           NO2 --> RR438 + O + NO                                                                   ', &
     '          H2O2 --> RR439 + 2 OH                                                                     ', &
     '            MP --> RR440 + OH + HO2 + CH2O                                                          ', &
     '          CH2O --> RR441 + H + CO + HO2                                                             ', &
     '          CH2O --> RR442 + CO + H2                                                                  ', &
     '          HNO3 --> RR443 + OH + NO2                                                                 ', &
     '          HNO2 --> RR444 + OH + NO                                                                  ', &
     '          HNO4 --> RR445 + NO3 + OH                                                                 ', &
     '          HNO4 --> RR446 + HO2 + NO2                                                                ', &
     '           NO3 --> RR447 + O + NO2                                                                  ', &
     '           NO3 --> RR448 + NO + O2                                                                  ', &
     '          N2O5 --> RR449 + NO3 + NO2                                                                ', &
     '          ALD2 --> RR450 + 0.12 MCO3 + 0.88 CO + HO2 + 0.88 MO2                                     ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_15 = (/ &
     '          ALD2 --> RR451 + CH4 + CO                                                                 ', &
     '           PAN --> RR452 + 0.7 MCO3 + 0.3 NO3 + 0.3 MO2 + 0.7 NO2                                   ', &
     '          RCHO --> RR453 + ETO2 + CO + HO2                                                          ', &
     '          ACET --> RR454 + MCO3 + MO2                                                               ', &
     '          ACET --> RR455 + CO + 2 MO2                                                               ', &
     '           MEK --> RR456 + 0.85 ETO2 + 0.15 RCO3 + 0.85 MCO3 + 0.15 MO2 ... etc.                    ', &
     '          GLYC --> RR457 + CO + 0.07 OH + 1.73 HO2 + 0.9 CH2O + 0.1 MOH ... etc.                    ', &
     '          GLYX --> RR458 + 2 CO + 2 HO2                                                             ', &
     '          GLYX --> RR459 + 2 CO + H2                                                                ', &
     '          GLYX --> RR460 + CO + CH2O                                                                ', &
     '          MGLY --> RR461 + MCO3 + CO + HO2                                                          ', &
     '           MVK --> RR462 + PRPE + CO                                                                ', &
     '           MVK --> RR463 + MCO3 + CO + HO2 + CH2O                                                   ', &
     '           MVK --> RR464 + RCO3 + MO2                                                               ', &
     '          MACR --> RR465 + MCO3 + CO + HO2 + CH2O                                                   ', &
     '           HAC --> RR466 + MCO3 + HO2 + CH2O                                                        ', &
     '          INPN --> RR467 + RCHO + OH + HO2 + NO2                                                    ', &
     '          PRPN --> RR468 + RCHO + OH + HO2 + NO2                                                    ', &
     '           ETP --> RR469 + ALD2 + OH + HO2                                                          ', &
     '          RA3P --> RR470 + RCHO + OH + HO2                                                          ', &
     '          RB3P --> RR471 + ACET + OH + HO2                                                          ', &
     '           R4P --> RR472 + RCHO + OH + HO2                                                          ', &
     '            PP --> RR473 + ALD2 + OH + HO2 + CH2O                                                   ', &
     '            RP --> RR474 + ALD2 + OH + HO2                                                          ', &
     '           RIP --> RR475 + 0.29 HC5 + 0.285 MACR + 0.425 MVK + OH + HO2 ... etc.                    ', &
     '           IAP --> RR476 + 0.26 GLYC + 0.36 HAC + 0.58 MGLY + 0.67 CO + OH ... etc.                 ', &
     '          ISNP --> RR477 + RCHO + OH + HO2 + NO2                                                    ', &
     '           VRP --> RR478 + 0.7 GLYC + 0.3 MGLY + 0.7 MCO3 + OH + 0.3 HO2 ... etc.                   ', &
     '           MRP --> RR479 + HAC + 0.5 CO + OH + HO2 + 0.5 CH2O                                       ', &
     '          MAOP --> RR480 + MCO3 + OH + CH2O                                                         ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_16 = (/ &
     '          R4N2 --> RR481 + 0.05 A3O2 + 0.18 B3O2 + 0.32 ACET + 0.32 ETO2 ... etc.                   ', &
     '           MAP --> RR482 + OH + MO2                                                                 ', &
     '         MACRN --> RR483 + HAC + MGLY + 0.5 CO + HO2 + 0.5 CH2O + NO2                               ', &
     '          MVKN --> RR484 + GLYC + MCO3 + NO2                                                        ', &
     '        ISOPNB --> RR485 + HC5 + HO2 + NO2                                                          ', &
     '           Br2 --> RR486 + 2 Br                                                                     ', &
     '           BrO --> RR487 + O + Br                                                                   ', &
     '          HOBr --> RR488 + Br + OH                                                                  ', &
     '         BrNO3 --> RR489 + NO3 + Br                                                                 ', &
     '         BrNO3 --> RR490 + BrO + NO2                                                                ', &
     '         BrNO2 --> RR491 + Br + NO2                                                                 ', &
     '         CHBr3 --> RR492 + 3 Br                                                                     ', &
     '           MPN --> RR493 + NO3 + HO2 + CH2O                                                         ', &
     '           MPN --> RR494 + MO2 + NO2                                                                ', &
     '        ISOPND --> RR495 + HC5 + HO2 + NO2                                                          ', &
     '        PROPNN --> RR496 + CO + CH2O + MO2 + NO2                                                    ', &
     '         ATOOH --> RR497 + MCO3 + OH + CH2O                                                         ', &
     '           N2O --> RR498 + O1D + N2                                                                 ', &
     '           OCS --> RR499 + SO2 + CO                                                                 ', &
     '           SO4 --> RR500 + SO2 + 2 OH                                                               ', &
     '            NO --> RR501 + N + O                                                                    ', &
     '         CH3Br --> RR502 + Br + MO2                                                                 ', &
     '          BrCl --> RR503 + Cl + Br                                                                  ', &
     '           Cl2 --> RR504 + 2 Cl                                                                     ', &
     '           ClO --> RR505 + Cl + O                                                                   ', &
     '          OClO --> RR506 + ClO + O                                                                  ', &
     '         Cl2O2 --> RR507 + ClOO + Cl                                                                ', &
     '         ClNO2 --> RR508 + Cl + NO2                                                                 ', &
     '         ClNO3 --> RR509 + Cl + NO3                                                                 ', &
     '         ClNO3 --> RR510 + ClO + NO2                                                                ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(18) :: EQN_NAMES_17 = (/ &
     '          HOCl --> RR511 + Cl + OH                                                                  ', &
     '         CH3Cl --> RR512 + Cl + MO2                                                                 ', &
     '       CH3CCl3 --> RR513 + 3 Cl                                                                     ', &
     '          CCl4 --> RR514 + 4 Cl                                                                     ', &
     '         CFC11 --> RR515 + 3 Cl                                                                     ', &
     '         CFC12 --> RR516 + 2 Cl                                                                     ', &
     '        CFC113 --> RR517 + 3 Cl                                                                     ', &
     '        CFC114 --> RR518 + 2 Cl                                                                     ', &
     '        CFC115 --> RR519 + Cl                                                                       ', &
     '       HCFC123 --> RR520 + 2 Cl                                                                     ', &
     '      HCFC141b --> RR521 + 2 Cl                                                                     ', &
     '      HCFC142b --> RR522 + 2 Cl                                                                     ', &
     '        HCFC22 --> RR523 + 2 Cl                                                                     ', &
     '         H1301 --> RR524 + Br                                                                       ', &
     '         H1211 --> RR525 + Cl + Br                                                                  ', &
     '         H2402 --> RR526 + 2 Br                                                                     ', &
     '        CH2Br2 --> RR527 + 2 Br                                                                     ', &
     '          ClOO --> RR528 + Cl + O2                                                                  ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(528) :: EQN_NAMES = (/&
    EQN_NAMES_0, EQN_NAMES_1, EQN_NAMES_2, EQN_NAMES_3, EQN_NAMES_4, &
    EQN_NAMES_5, EQN_NAMES_6, EQN_NAMES_7, EQN_NAMES_8, EQN_NAMES_9, &
    EQN_NAMES_10, EQN_NAMES_11, EQN_NAMES_12, EQN_NAMES_13, EQN_NAMES_14, &
    EQN_NAMES_15, EQN_NAMES_16, EQN_NAMES_17 /)

! INLINED global variables

! End INLINED global variables


END MODULE gckpp_Monitor
