---
### geoschem_config.yml: GEOS-Chem Runtime configuration options.
### Customized for simulations using the KPP "fullchem" mechanism.
###
### NOTE: Add quotes around nitrogen oxide ('NO'), because YAML
### parsers will confuse this with a negative "no" value.
###
### Customized for WRF-GC, Haipeng Lin, August 2022
### Note: Most of configuration options here do not need to be changed
### when running in the WRF-GC environment!

#============================================================================
# Simulation settings
#============================================================================
simulation:
  name: fullchem
  start_date: [19970215, 031100]
  end_date: [20180415, 040000]
  root_data_dir: /n/holyscratch01/external_repos/GEOS-CHEM/gcgrid/data/ExtData
  chem_inputs_dir: /n/holyscratch01/external_repos/GEOS-CHEM/gcgrid/data/ExtData/CHEM_INPUTS/
  met_field: GEOSFP
  species_database_file: ./species_database.yml
  species_metadata_output_file: ./geoschem_species_metadata.yml
  debug_printout: false
  use_gcclassic_timers: false

#============================================================================
# Settings for GEOS-Chem operations
#============================================================================
operations:

  chemistry:
    activate: true
    linear_chemistry_aloft:
      activate: true
      use_linoz_for_O3: true
    active_strat_H2O:
      activate: true
      use_static_bnd_cond: true
    gamma_HO2: 0.2
    autoreduce_solver:
      activate: false
      use_target_threshold:
        activate: true
        oh_tuning_factor: 0.00005
        no2_tuning_factor: 0.0001
      use_absolute_threshold:
        scale_by_pressure: true
        absolute_threshold: 100.0
      keep_halogens_active: false
      append_in_internal_timestep: false

  convection:
    activate: true

  dry_deposition:
    activate: true
    CO2_effect:
      activate: false
      CO2_level: 600.0
      reference_CO2_level: 380.0
    diag_alt_above_sfc_in_m: 10

  pbl_mixing:
     activate: true
     use_non_local_pbl: true 

  photolysis:
    input_dir: /n/holyscratch01/external_repos/GEOS-CHEM/gcgrid/data/ExtData/CHEM_INPUTS/FAST_JX/v2021-10/
    num_levs_with_cloud: 20
    overhead_O3:
      use_online_O3_from_model: true 
      use_column_O3_from_met: true
      use_TOMS_SBUV_O3: false
    photolyze_nitrate_aerosol:
      activate: false
      NITs_Jscale_JHNO3: 0.0
      NIT_Jscale_JHNO2: 0.0
      percent_channel_A_HONO: 66.667
      percent_channel_B_NO2: 33.333

  rrtmg_rad_transfer_model:
    activate: false
    aod_wavelengths_in_nm:
      - 550
    longwave_fluxes: false
    shortwave_fluxes: false
    clear_sky_flux: false
    all_sky_flux: false

  transport:
    activate: true
    transported_species:
      - ACET
      - ACTA
      - AERI
      - ALD2
      - ALK4
      - AONITA
      - AROMP4
      - AROMP5
      - ATOOH
      - BALD
      - BCPI
      - BCPO
      - BENZ
      - BENZP
      - Br
      - Br2
      - BrCl
      - BrNO2
      - BrNO3
      - BrO
      - BrSALA
      - BrSALC
      - BZCO3H
      - BZPAN
      - C2H2
      - C2H4
      - C2H6
      - C3H8
      - CCl4
      - CFC11
      - CFC113
      - CFC114
      - CFC115
      - CFC12
      - CH2Br2
      - CH2Cl2
      - CH2I2
      - CH2IBr
      - CH2ICl
      - CH2O
      - CH3Br
      - CH3CCl3
      - CH3Cl
      - CH3I
      - CH4
      - CHBr3
      - CHCl3
      - Cl
      - Cl2
      - Cl2O2
      - ClNO2
      - ClNO3
      - ClO
      - ClOO
      - CLOCK
      - CO
      - CSL
      - DMS
      - DST1
      - DST2
      - DST3
      - DST4
      - EOH
      - ETHLN
      - ETHN
      - ETHP
      - ETNO3
      - ETP
      - GLYC
      - GLYX
      - H1211
      - H1301
      - H2402
      - H2O
      - H2O2
      - HAC
      - HBr
      - HC5A
      - HCFC123
      - HCFC141b
      - HCFC142b
      - HCFC22
      - HCl
      - HCOOH
      - HI
      - HMHP
      - HMML
      - HMS
      - HNO2
      - HNO3
      - HNO4
      - HOBr
      - HOCl
      - HOI
      - HONIT
      - HPALD1
      - HPALD2
      - HPALD3
      - HPALD4
      - HPETHNL
      - I
      - I2
      - I2O2
      - I2O3
      - I2O4
      - IBr
      - ICHE
      - ICl
      - ICN
      - ICPDH
      - IDC
      - IDCHP
      - IDHDP
      - IDHPE
      - IDN
      - IEPOXA
      - IEPOXB
      - IEPOXD
      - IHN1
      - IHN2
      - IHN3
      - IHN4
      - INDIOL
      - INO
      - INPB
      - INPD
      - IO
      - IONITA
      - IONO
      - IONO2
      - IPRNO3
      - ISALA
      - ISALC
      - ISOP
      - ITCN
      - ITHN
      - LIMO
      - LVOC
      - LVOCOA
      - MACR
      - MACR1OOH
      - MAP
      - MCRDH
      - MCRENOL
      - MCRHN
      - MCRHNB
      - MCRHP
      - MCT
      - MEK
      - MENO3
      - MGLY
      - MOH
      - MONITA
      - MONITS
      - MONITU
      - MP
      - MPAN
      - MPN
      - MSA
      - MTPA
      - MTPO
      - MVK
      - MVKDH
      - MVKHC
      - MVKHCB
      - MVKHP
      - MVKN
      - MVKPC
      - N2O
      - N2O5
      - NH3
      - NH4
      - NIT
      - NITs
      - 'NO'
      - NO2
      - NO3
      - NPHEN
      - NPRNO3
      - O3
      - OClO
      - OCPI
      - OCPO
      - OCS
      - OIO
      - PAN
      - pFe
      - PHEN
      - PIP
      - PP
      - PPN
      - PROPNN
      - PRPE
      - PRPN
      - PYAC
      - R4N2
      - R4P
      - RA3P
      - RB3P
      - RCHO
      - RIPA
      - RIPB
      - RIPC
      - RIPD
      - RP
      - SALA
      - SALAAL
      - SALACL
      - SALC
      - SALCAL
      - SALCCL
      - SO2
      - SO4
      - SO4s
      - SOAGX
      - SOAIE
      - SOAS
      - SOAP
      - TOLU
      - XYLE

  wet_deposition:
    activate: true

#============================================================================
# Settings for GEOS-Chem aerosols
#============================================================================
aerosols:

  carbon:
    activate: true
    brown_carbon: false
    enhance_black_carbon_absorption:
      activate: true
      hydrophilic: 1.5
      hydrophobic: 1.0

  complex_SOA:
    activate:  false
    semivolatile_POA: false

  dust:
    activate: true
    acid_uptake_on_dust: false

  sea_salt:
    activate: true
    SALA_radius_bin_in_um: [0.01, 0.5]
    SALC_radius_bin_in_um: [0.5,  8.0]
    marine_organic_aerosols: false

  stratosphere:
    settle_strat_aerosol: true
    polar_strat_clouds:
      activate: true
      het_chem: true
    allow_homogeneous_NAT: false
    NAT_supercooling_req_in_K: 3.0
    supersat_factor_req_for_ice_nucl: 1.2
    calc_strat_aod: true

  sulfate:
    activate: true
    metal_cat_SO2_oxidation: true

#============================================================================
# Settings for diagnostics (other than HISTORY and HEMCO)
#============================================================================
extra_diagnostics:

  obspack:
    activate: false
    quiet_logfile_output: false
    input_file: ./obspack_co2_1_OCO2MIP_2018-11-28.YYYYMMDD.nc
    output_file: ./OutputDir/GEOSChem.ObsPack.YYYYMMDD_hhmmz.nc4
    output_species:
      - CO
      - 'NO'
      - O3

  planeflight:
    activate: false
    flight_track_file: Planeflight.dat.YYYYMMDD
    output_file: plane.log.YYYYMMDD
