---
### geoschem_config.yml: GEOS-Chem Runtime configuration options.
### Customized for GCHP simulations using the KPP "fullchem" mechanism.
###
### NOTE: Add quotes around nitrogen oxide ('NO'), because YAML
### parsers will confuse this with a negative "no" value.

#============================================================================
# Simulation settings
#============================================================================
simulation:
  name: fullchem
  start_date: 20000101 000000
  end_date: 20000101 010000
  chem_inputs_dir: ./
  species_database_file: ./species_database.yml
  verbose:
    activate: false
    on_cores: root       # Allowed values: root all

#============================================================================
# Settings for GEOS-Chem operations
#============================================================================
operations:

  chemistry:
    activate: true
    linear_chemistry_aloft:
      activate: true
      use_linoz_for_O3: true
    active_strat_H2O:
      activate: true
      use_static_bnd_cond: true
    gamma_HO2: 0.2
    autoreduce_solver:
      activate: false
      use_target_threshold:
        activate: true
        oh_tuning_factor: 0.00005
        no2_tuning_factor: 0.0001
      use_absolute_threshold:
        scale_by_pressure: true
        absolute_threshold: 100.0
      keep_halogens_active: false
      append_in_internal_timestep: false

  photolysis:
    activate: true
    cloud-j:
      num_levs_with_cloud: 22
      cloud_scheme_flag: 3
      opt_depth_increase_factor: 1.050
      min_top_inserted_cloud_OD: 0.005
      cloud_overlap_correlation: 0.33
      num_cloud_overlap_blocks: 6
      sphere_correction: 1
      num_wavelength_bins: 18
      use_H2O_UV_absorption: true
    input_directories:
      fastjx_input_dir: /see/namelist/file
      cloudj_input_dir: /see/namelist/file
    overhead_O3:
      use_online_O3_from_model: true
      use_column_O3_from_met: true
      use_TOMS_SBUV_O3: false
    photolyze_nitrate_aerosol:
      activate: true
      NITs_Jscale: 100.0
      NIT_Jscale: 100.0
      percent_channel_A_HONO: 66.667
      percent_channel_B_NO2: 33.333

  dry_deposition:
    activate: true
    CO2_effect:
      activate: false
      CO2_level: 600.0
      reference_CO2_level: 380.0
    diag_alt_above_sfc_in_m: 10

  wet_deposition:
    activate: true

  pbl_mixing:
     activate: true
     use_non_local_pbl: true

  convection:
    activate: false

  rrtmg_rad_transfer_model:
    activate: false
    aod_wavelengths_in_nm:
      - 550
    longwave_fluxes: false
    shortwave_fluxes: false
    clear_sky_flux: false
    all_sky_flux: false

  transport:
    transported_species:
      - ACET
      - ACR
      - ACTA
      - AERI
      - ALD2
      - ALK4
      - ALK4N2
      - ALK4P
      - ALK6
      - AONITA
      - APAN
      - APINN
      - APINP
      - AROMCHO
      - AROMP4
      - AROMP5
      - AROMPN
      - ASOA1
      - ASOA2
      - ASOA3
      - ASOAN
      - ASOG1
      - ASOG2
      - ASOG3
      - ATOOH
      - BALD
      - BCPI
      - BCPO
      - BENZ
      - BENZP
      - BPINN
      - BPINO
      - BPINON
      - BPINOOH
      - BPINP
      - Br
      - Br2
      - BrCl
      - BrNO2
      - BrNO3
      - BrO
      - BrSALA
      - BrSALC
      - BUTDI
      - BUTN
      - BZCO3H
      - BZPAN
      - C2H2
      - C2H4
      - C2H6
      - C3H8
      - C4H6
      - C96N
      - C96O2H
      - CCl4
      - CFC11
      - CFC113
      - CFC114
      - CFC115
      - CFC12
      - CH2Br2
      - CH2Cl2
      - CH2I2
      - CH2IBr
      - CH2ICl
      - CH2O
      - CH3Br
      - CH3CCl3
      - CH3Cl
      - CH3I
      - CH4
      - CHBr3
      - CHCl3
      - Cl
      - Cl2
      - Cl2O2
      - ClNO2
      - ClNO3
      - ClO
      - ClOO
      - CLOCK
      - CO
      - CSL
      - DMS
      - DST1
      - DST2
      - DST3
      - DST4
      - EBZ
      - EOH
      - ETHLN
      - ETHN
      - ETHP
      - ETNO3
      - ETP
      - FURA
      - GLYC
      - GLYX
      - H1211
      - H1301
      - H2402
      - H2O
      - H2O2
      - HAC
      - HACTA
      - HBr
      - HC5A
      - HCFC123
      - HCFC141b
      - HCFC142b
      - HCFC22
      - HCl
      - HCOOH
      - HI
      - HMHP
      - HMML
      - HMS
      - HNO2
      - HNO3
      - HNO4
      - HOBr
      - HOCl
      - HOI
      - HONIT
      - HPALD1
      - HPALD2
      - HPALD3
      - HPALD4
      - HPETHNL
      - I
      - I2
      - I2O2
      - I2O3
      - I2O4
      - IBr
      - ICHE
      - ICl
      - ICN
      - ICPDH
      - IDC
      - IDCHP
      - IDHDP
      - IDHPE
      - IDN
      - IEPOXA
      - IEPOXB
      - IEPOXD
      - IHN1
      - IHN2
      - IHN3
      - IHN4
      - INDIOL
      - INO
      - INPB
      - INPD
      - IO
      - IONITA
      - IONO
      - IONO2
      - IPRNO3
      - ISALA
      - ISALC
      - ISOP
      - ITCN
      - ITHN
      - LIMAL
      - LIMKB
      - LIMKET
      - LIMN
      - LIMNB
      - LIMO
      - LIMO2H
      - LIMO3H
      - LIMPAN
      - LVOC
      - LVOCOA
      - MACR
      - MACR1OOH
      - MAP
      - MCRDH
      - MCRENOL
      - MCRHN
      - MCRHNB
      - MCRHP
      - MCT
      - MEK
      - MEKPN
      - MENO3
      - MGLY
      - MOH
      - MONITA
      - MONITS
      - MONITU
      - MP
      - MPAN
      - MPN
      - MSA
      - MTPA
      - MTPO
      - MVK
      - MVKDH
      - MVKHC
      - MVKHCB
      - MVKHP
      - MVKN
      - MVKPC
      - MYRCO
      - N2O
      - N2O5
      - NH3
      - NH4
      - NIT
      - NITs
      - 'NO'
      - NO2
      - NO3
      - NPHEN
      - NPRNO3
      - O3
      - OClO
      - OCPI
      - OCPO
      - OCS
      - OIO
      - PAN
      - pFe
      - PHAN
      - PHEN
      - PIN
      - PINAL
      - PINO3H
      - PINONIC
      - PINPAN
      - PIP
      - PP
      - PPN
      - PROPNN
      - PRPE
      - PRPN
      - PYAC
      - R4N2
      - R4P
      - R7N2
      - R7P
      - RA3P
      - RB3P
      - RCHO
      - RCOOH
      - RIPA
      - RIPB
      - RIPC
      - RIPD
      - RNO3
      - RP
      - SALA
      - SALAAL
      - SALACL
      - SALC
      - SALCAL
      - SALCCL
      - SO2
      - SO4
      - SO4s
      - SOAGX
      - SOAIE
      - STYR
      - TLFUONE
      - TMB
      - TOLU
      - TSOA0
      - TSOA1
      - TSOA2
      - TSOA3
      - TSOG0
      - TSOG1
      - TSOG2
      - TSOG3
      - XYLE

#============================================================================
# Settings for GEOS-Chem aerosols
#============================================================================
aerosols:

  optics:
    input_dir: /see/namelist/file

  carbon:
    activate: true
    brown_carbon: false
    enhance_black_carbon_absorption:
      activate: true
      hydrophilic: 1.5
      hydrophobic: 1.0

  complex_SOA:
    activate:  true
    semivolatile_POA: false

  dust:
    activate: true
    acid_uptake_on_dust: false

  sea_salt:
    activate: true
    SALA_radius_bin_in_um: [0.01, 0.5]
    SALC_radius_bin_in_um: [0.5,  8.0]
    marine_organic_aerosols: false

  stratosphere:
    settle_strat_aerosol: true
    polar_strat_clouds:
      activate: true
      het_chem: true
    allow_homogeneous_NAT: false
    NAT_supercooling_req_in_K: 3.0
    supersat_factor_req_for_ice_nucl: 1.2
    calc_strat_aod: true

  sulfate:
    activate: true
    metal_cat_SO2_oxidation: true
