#!/bin/bash

#SBATCH -n 96
#SBATCH -N 2
#SBATCH --exclusive
#SBATCH -t 0-8:00
#SBATCH -p huce_cascade
#SBATCH --mem=180000
#SBATCH --mail-type=END

# Define log name to include simulation start date
start_str=$(echo $(cat cap_restart) | sed 's/ /_/g')
log=gchp.${start_str}z.log
echo "Writing output to ${log}"

# Update config files, set restart symlink, load run env, and do sanity checks
source setCommonRunSettings.sh > ${log}
source setRestartLink.sh >> ${log}
source gchp.env >> ${log}
source checkRunSettings.sh >> ${log}

# Cannon-specific setting to get around connection issues at high # cores
export OMPI_MCL_btl=openib

# Run GCHP and evenly distribute tasks across nodes
NX=$( grep NX GCHP.rc | awk '{print $2}' )
NY=$( grep NY GCHP.rc | awk '{print $2}' )
coreCount=$(( ${NX} * ${NY} ))
planeCount=$(( ${coreCount} / ${SLURM_NNODES} ))
if [[ $(( ${coreCount} % ${SLURM_NNODES} )) > 0 ]]; then
	${planeCount}=$(( ${planeCount} + 1 ))
fi
time srun -n ${coreCount} -N ${SLURM_NNODES} -m plane=${planeCount} --mpi=pmix ./gchp >> ${log}

# Rename and move restart file and update restart symlink if new start time ok
new_start_str=$(echo $(cat cap_restart) | sed 's/ /_/g')
if [[ "${new_start_str}" = "${start_str}" || "${new_start_str}" = "" ]]; then
   echo "ERROR: cap_restart either did not change or is empty."
   exit 1
else
    N=$(grep "CS_RES=" setCommonRunSettings.sh | cut -c 8- | xargs )    
    mv gcchem_internal_checkpoint Restarts/GEOSChem.Restart.${new_start_str}z.c${N}.nc4
    source setRestartLink.sh
fi

exit 0
