!                          -------------------
!                          W  A  R  N  I  N  G
!                          -------------------
!
!   This code fragment is automatically generated by mapl_acg.
!   Please DO NOT edit it. Any modification made in here will be overwritten
!   next time this file is auto-generated. Instead, enter your additions
!   or deletions in the .rc file. 
!


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'WD_HNO3',  &
        LONG_NAME          = 'HNO3 lost to wet deposition',  &
        UNITS              = 'kg/s', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'WD_H2O2',  &
        LONG_NAME          = 'H2O2 lost to wet deposition',  &
        UNITS              = 'kg/s', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'WD_CH2O',  &
        LONG_NAME          = 'CH2O lost to wet deposition',  &
        UNITS              = 'kg/s', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'WD_MP',  &
        LONG_NAME          = 'MP lost to wet deposition',  &
        UNITS              = 'kg/s', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'WD_SO2',  &
        LONG_NAME          = 'SO2 lost to wet deposition',  &
        UNITS              = 'kg/s', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'WD_SO4',  &
        LONG_NAME          = 'SO4 lost to wet deposition',  &
        UNITS              = 'kg/s', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'WD_SO4s',  &
        LONG_NAME          = 'SO4s lost to wet deposition',  &
        UNITS              = 'kg/s', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'WD_MSA',  &
        LONG_NAME          = 'MSA lost to wet deposition',  &
        UNITS              = 'kg/s', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'WD_NH3',  &
        LONG_NAME          = 'NH3 lost to wet deposition',  &
        UNITS              = 'kg/s', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'WD_NH4',  &
        LONG_NAME          = 'NH4 lost to wet deposition',  &
        UNITS              = 'kg/s', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'WD_NIT',  &
        LONG_NAME          = 'NIT lost to wet deposition',  &
        UNITS              = 'kg/s', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'WD_NITs',  &
        LONG_NAME          = 'NITs lost to wet deposition',  &
        UNITS              = 'kg/s', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'WD_BCPI',  &
        LONG_NAME          = 'BCPI lost to wet deposition',  &
        UNITS              = 'kg/s', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'WD_OCPI',  &
        LONG_NAME          = 'OCPI lost to wet deposition',  &
        UNITS              = 'kg/s', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'WD_BCPO',  &
        LONG_NAME          = 'BCPO lost to wet deposition',  &
        UNITS              = 'kg/s', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'WD_OCPO',  &
        LONG_NAME          = 'OCPO lost to wet deposition',  &
        UNITS              = 'kg/s', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'WD_ALPH',  &
        LONG_NAME          = 'ALPH lost to wet deposition',  &
        UNITS              = 'kg/s', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'WD_LIMO',  &
        LONG_NAME          = 'LIMO lost to wet deposition',  &
        UNITS              = 'kg/s', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'WD_ALCO',  &
        LONG_NAME          = 'ALCO lost to wet deposition',  &
        UNITS              = 'kg/s', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'WD_SOG1',  &
        LONG_NAME          = 'SOG1 lost to wet deposition',  &
        UNITS              = 'kg/s', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'WD_SOG2',  &
        LONG_NAME          = 'SOG2 lost to wet deposition',  &
        UNITS              = 'kg/s', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'WD_SOG3',  &
        LONG_NAME          = 'SOG3 lost to wet deposition',  &
        UNITS              = 'kg/s', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'WD_SOG4',  &
        LONG_NAME          = 'SOG4 lost to wet deposition',  &
        UNITS              = 'kg/s', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'WD_SOA1',  &
        LONG_NAME          = 'SOA1 lost to wet deposition',  &
        UNITS              = 'kg/s', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'WD_SOA2',  &
        LONG_NAME          = 'SOA2 lost to wet deposition',  &
        UNITS              = 'kg/s', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'WD_SOA3',  &
        LONG_NAME          = 'SOA3 lost to wet deposition',  &
        UNITS              = 'kg/s', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'WD_SOA4',  &
        LONG_NAME          = 'SOA4 lost to wet deposition',  &
        UNITS              = 'kg/s', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'WD_DST1',  &
        LONG_NAME          = 'DST1 lost to wet deposition',  &
        UNITS              = 'kg/s', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'WD_DST2',  &
        LONG_NAME          = 'DST2 lost to wet deposition',  &
        UNITS              = 'kg/s', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'WD_DST3',  &
        LONG_NAME          = 'DST3 lost to wet deposition',  &
        UNITS              = 'kg/s', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'WD_DST4',  &
        LONG_NAME          = 'DST4 lost to wet deposition',  &
        UNITS              = 'kg/s', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'WD_SALA',  &
        LONG_NAME          = 'SALA lost to wet deposition',  &
        UNITS              = 'kg/s', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'WD_SALC',  &
        LONG_NAME          = 'SALC lost to wet deposition',  &
        UNITS              = 'kg/s', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FX_NOx',  &
        LONG_NAME          = 'NOx drydep flux',  &
        UNITS              = 'kg/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FX_O3',  &
        LONG_NAME          = 'O3 drydep flux',  &
        UNITS              = 'kg/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FX_PAN',  &
        LONG_NAME          = 'PAN drydep flux',  &
        UNITS              = 'kg/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FX_HNO3',  &
        LONG_NAME          = 'HNO3 drydep flux',  &
        UNITS              = 'kg/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FX_H2O2',  &
        LONG_NAME          = 'H2O2 drydep flux',  &
        UNITS              = 'kg/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FX_N2O5',  &
        LONG_NAME          = 'N2O5 drydep flux',  &
        UNITS              = 'kg/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FX_PPN',  &
        LONG_NAME          = 'PPN drydep flux',  &
        UNITS              = 'kg/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FX_R4N2',  &
        LONG_NAME          = 'R4N2 drydep flux',  &
        UNITS              = 'kg/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FX_CH2O',  &
        LONG_NAME          = 'CH2O drydep flux',  &
        UNITS              = 'kg/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FX_SO2',  &
        LONG_NAME          = 'SO2 drydep flux',  &
        UNITS              = 'kg/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FX_SO4',  &
        LONG_NAME          = 'SO4 drydep flux',  &
        UNITS              = 'kg/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FX_SO4S',  &
        LONG_NAME          = 'SO4s drydep flux',  &
        UNITS              = 'kg/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FX_MSA',  &
        LONG_NAME          = 'MSA drydep flux',  &
        UNITS              = 'kg/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FX_NH3',  &
        LONG_NAME          = 'NH3 drydep flux',  &
        UNITS              = 'kg/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FX_NH4',  &
        LONG_NAME          = 'NH4 drydep flux',  &
        UNITS              = 'kg/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FX_NIT',  &
        LONG_NAME          = 'NIT drydep flux',  &
        UNITS              = 'kg/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FX_NITS',  &
        LONG_NAME          = 'NITs drydep flux',  &
        UNITS              = 'kg/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FX_BCPI',  &
        LONG_NAME          = 'BCPI drydep flux',  &
        UNITS              = 'kg/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FX_OCPI',  &
        LONG_NAME          = 'OCPI drydep flux',  &
        UNITS              = 'kg/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FX_BCPO',  &
        LONG_NAME          = 'BCPO drydep flux',  &
        UNITS              = 'kg/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FX_OCPO',  &
        LONG_NAME          = 'OCPO drydep flux',  &
        UNITS              = 'kg/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FX_ALPH',  &
        LONG_NAME          = 'ALPH drydep flux',  &
        UNITS              = 'kg/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FX_LIMO',  &
        LONG_NAME          = 'LIMO drydep flux',  &
        UNITS              = 'kg/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FX_ALCO',  &
        LONG_NAME          = 'ALCO drydep flux',  &
        UNITS              = 'kg/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FX_SOG1',  &
        LONG_NAME          = 'SOG1 drydep flux',  &
        UNITS              = 'kg/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FX_SOG2',  &
        LONG_NAME          = 'SOG2 drydep flux',  &
        UNITS              = 'kg/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FX_SOG3',  &
        LONG_NAME          = 'SOG3 drydep flux',  &
        UNITS              = 'kg/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FX_SOG4',  &
        LONG_NAME          = 'SOG4 drydep flux',  &
        UNITS              = 'kg/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FX_SOA1',  &
        LONG_NAME          = 'SOA1 drydep flux',  &
        UNITS              = 'kg/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FX_SOA2',  &
        LONG_NAME          = 'SOA2 drydep flux',  &
        UNITS              = 'kg/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FX_SOA3',  &
        LONG_NAME          = 'SOA3 drydep flux',  &
        UNITS              = 'kg/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FX_SOA4',  &
        LONG_NAME          = 'SOA4 drydep flux',  &
        UNITS              = 'kg/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FX_DST1',  &
        LONG_NAME          = 'DST1 drydep flux',  &
        UNITS              = 'kg/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FX_DST2',  &
        LONG_NAME          = 'DST2 drydep flux',  &
        UNITS              = 'kg/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FX_DST3',  &
        LONG_NAME          = 'DST3 drydep flux',  &
        UNITS              = 'kg/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FX_DST4',  &
        LONG_NAME          = 'DST4 drydep flux',  &
        UNITS              = 'kg/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FX_SALA',  &
        LONG_NAME          = 'SALA drydep flux',  &
        UNITS              = 'kg/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FX_SALC',  &
        LONG_NAME          = 'SALC drydep flux',  &
        UNITS              = 'kg/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FQ_NOx',  &
        LONG_NAME          = 'NOx drydep frequency',  &
        UNITS              = '1/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FQ_O3',  &
        LONG_NAME          = 'O3 drydep frequency',  &
        UNITS              = '1/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FQ_PAN',  &
        LONG_NAME          = 'PAN drydep frequency',  &
        UNITS              = '1/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FQ_HNO3',  &
        LONG_NAME          = 'HNO3 drydep frequency',  &
        UNITS              = '1/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FQ_H2O2',  &
        LONG_NAME          = 'H2O2 drydep frequency',  &
        UNITS              = '1/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FQ_N2O5',  &
        LONG_NAME          = 'N2O5 drydep frequency',  &
        UNITS              = '1/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FQ_PPN',  &
        LONG_NAME          = 'PPN drydep frequency',  &
        UNITS              = '1/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FQ_R4N2',  &
        LONG_NAME          = 'R4N2 drydep frequency',  &
        UNITS              = '1/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FQ_CH2O',  &
        LONG_NAME          = 'CH2O drydep frequency',  &
        UNITS              = '1/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FQ_SO2',  &
        LONG_NAME          = 'SO2 drydep frequency',  &
        UNITS              = '1/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FQ_SO4',  &
        LONG_NAME          = 'SO4 drydep frequency',  &
        UNITS              = '1/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FQ_SO4S',  &
        LONG_NAME          = 'SO4s drydep frequency',  &
        UNITS              = '1/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FQ_MSA',  &
        LONG_NAME          = 'MSA drydep frequency',  &
        UNITS              = '1/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FQ_NH3',  &
        LONG_NAME          = 'NH3 drydep frequency',  &
        UNITS              = '1/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FQ_NH4',  &
        LONG_NAME          = 'NH4 drydep frequency',  &
        UNITS              = '1/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FQ_NIT',  &
        LONG_NAME          = 'NIT drydep frequency',  &
        UNITS              = '1/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FQ_NITS',  &
        LONG_NAME          = 'NITs drydep frequency',  &
        UNITS              = '1/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FQ_BCPI',  &
        LONG_NAME          = 'BCPI drydep frequency',  &
        UNITS              = '1/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FQ_OCPI',  &
        LONG_NAME          = 'OCPI drydep frequency',  &
        UNITS              = '1/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FQ_BCPO',  &
        LONG_NAME          = 'BCPO drydep frequency',  &
        UNITS              = '1/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FQ_OCPO',  &
        LONG_NAME          = 'OCPO drydep frequency',  &
        UNITS              = '1/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FQ_ALPH',  &
        LONG_NAME          = 'ALPH drydep frequency',  &
        UNITS              = '1/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FQ_LIMO',  &
        LONG_NAME          = 'LIMO drydep frequency',  &
        UNITS              = '1/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FQ_ALCO',  &
        LONG_NAME          = 'ALCO drydep frequency',  &
        UNITS              = '1/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FQ_SOG1',  &
        LONG_NAME          = 'SOG1 drydep frequency',  &
        UNITS              = '1/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FQ_SOG2',  &
        LONG_NAME          = 'SOG2 drydep frequency',  &
        UNITS              = '1/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FQ_SOG3',  &
        LONG_NAME          = 'SOG3 drydep frequency',  &
        UNITS              = '1/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FQ_SOG4',  &
        LONG_NAME          = 'SOG4 drydep frequency',  &
        UNITS              = '1/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FQ_SOA1',  &
        LONG_NAME          = 'SOA1 drydep frequency',  &
        UNITS              = '1/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FQ_SOA2',  &
        LONG_NAME          = 'SOA2 drydep frequency',  &
        UNITS              = '1/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FQ_SOA3',  &
        LONG_NAME          = 'SOA3 drydep frequency',  &
        UNITS              = '1/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FQ_SOA4',  &
        LONG_NAME          = 'SOA4 drydep frequency',  &
        UNITS              = '1/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FQ_DST1',  &
        LONG_NAME          = 'DST1 drydep frequency',  &
        UNITS              = '1/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FQ_DST2',  &
        LONG_NAME          = 'DST2 drydep frequency',  &
        UNITS              = '1/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FQ_DST3',  &
        LONG_NAME          = 'DST3 drydep frequency',  &
        UNITS              = '1/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FQ_DST4',  &
        LONG_NAME          = 'DST4 drydep frequency',  &
        UNITS              = '1/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FQ_SALA',  &
        LONG_NAME          = 'SALA drydep frequency',  &
        UNITS              = '1/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_FQ_SALC',  &
        LONG_NAME          = 'SALC drydep frequency',  &
        UNITS              = '1/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_V_NOx',  &
        LONG_NAME          = 'NOx drydep velocity',  &
        UNITS              = 'm/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_V_O3',  &
        LONG_NAME          = 'O3 drydep velocity',  &
        UNITS              = 'm/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_V_PAN',  &
        LONG_NAME          = 'PAN drydep velocity',  &
        UNITS              = 'm/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_V_HNO3',  &
        LONG_NAME          = 'HNO3 drydep velocity',  &
        UNITS              = 'm/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_V_H2O2',  &
        LONG_NAME          = 'H2O2 drydep velocity',  &
        UNITS              = 'm/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_V_N2O5',  &
        LONG_NAME          = 'N2O5 drydep velocity',  &
        UNITS              = 'm/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_V_PPN',  &
        LONG_NAME          = 'PPN drydep velocity',  &
        UNITS              = 'm/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_V_R4N2',  &
        LONG_NAME          = 'R4N2 drydep velocity',  &
        UNITS              = 'm/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_V_CH2O',  &
        LONG_NAME          = 'CH2O drydep velocity',  &
        UNITS              = 'm/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_V_SO2',  &
        LONG_NAME          = 'SO2 drydep velocity',  &
        UNITS              = 'm/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_V_SO4',  &
        LONG_NAME          = 'SO4 drydep velocity',  &
        UNITS              = 'm/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_V_SO4S',  &
        LONG_NAME          = 'SO4s drydep velocity',  &
        UNITS              = 'm/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_V_MSA',  &
        LONG_NAME          = 'MSA drydep velocity',  &
        UNITS              = 'm/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_V_NH3',  &
        LONG_NAME          = 'NH3 drydep velocity',  &
        UNITS              = 'm/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_V_NH4',  &
        LONG_NAME          = 'NH4 drydep velocity',  &
        UNITS              = 'm/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_V_NIT',  &
        LONG_NAME          = 'NIT drydep velocity',  &
        UNITS              = 'm/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_V_NITS',  &
        LONG_NAME          = 'NITs drydep velocity',  &
        UNITS              = 'm/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_V_BCPI',  &
        LONG_NAME          = 'BCPI drydep velocity',  &
        UNITS              = 'm/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_V_OCPI',  &
        LONG_NAME          = 'OCPI drydep velocity',  &
        UNITS              = 'm/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_V_BCPO',  &
        LONG_NAME          = 'BCPO drydep velocity',  &
        UNITS              = 'm/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_V_OCPO',  &
        LONG_NAME          = 'OCPO drydep velocity',  &
        UNITS              = 'm/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_V_ALPH',  &
        LONG_NAME          = 'ALPH drydep velocity',  &
        UNITS              = 'm/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_V_LIMO',  &
        LONG_NAME          = 'LIMO drydep velocity',  &
        UNITS              = 'm/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_V_ALCO',  &
        LONG_NAME          = 'ALCO drydep velocity',  &
        UNITS              = 'm/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_V_SOG1',  &
        LONG_NAME          = 'SOG1 drydep velocity',  &
        UNITS              = 'm/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_V_SOG2',  &
        LONG_NAME          = 'SOG2 drydep velocity',  &
        UNITS              = 'm/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_V_SOG3',  &
        LONG_NAME          = 'SOG3 drydep velocity',  &
        UNITS              = 'm/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_V_SOG4',  &
        LONG_NAME          = 'SOG4 drydep velocity',  &
        UNITS              = 'm/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_V_SOA1',  &
        LONG_NAME          = 'SOA1 drydep velocity',  &
        UNITS              = 'm/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_V_SOA2',  &
        LONG_NAME          = 'SOA2 drydep velocity',  &
        UNITS              = 'm/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_V_SOA3',  &
        LONG_NAME          = 'SOA3 drydep velocity',  &
        UNITS              = 'm/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_V_SOA4',  &
        LONG_NAME          = 'SOA4 drydep velocity',  &
        UNITS              = 'm/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_V_DST1',  &
        LONG_NAME          = 'DST1 drydep velocity',  &
        UNITS              = 'm/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_V_DST2',  &
        LONG_NAME          = 'DST2 drydep velocity',  &
        UNITS              = 'm/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_V_DST3',  &
        LONG_NAME          = 'DST3 drydep velocity',  &
        UNITS              = 'm/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_V_DST4',  &
        LONG_NAME          = 'DST4 drydep velocity',  &
        UNITS              = 'm/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_V_SALA',  &
        LONG_NAME          = 'SALA drydep velocity',  &
        UNITS              = 'm/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'DD_V_SALC',  &
        LONG_NAME          = 'SALC drydep velocity',  &
        UNITS              = 'm/s', &
        DIMS               = MAPL_DimsHorzOnly,    &
        VLOCATION          = MAPL_VLocationNone,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)

