! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Parameter Module File
! 
! Generated by KPP-2.2.4_gc symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : gckpp_Parameters.f90
! Time                 : Thu Mar 23 14:12:41 2017
! Working directory    : /short/m19/jaf574/GC.v11-01/Code.v11-01/KPP/Standard
! Equation file        : gckpp.kpp
! Output root filename : gckpp
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE gckpp_Parameters

  USE gckpp_Precision
  PUBLIC
  SAVE


! NSPEC - Number of chemical species
  INTEGER, PARAMETER :: NSPEC = 178 
! NVAR - Number of Variable species
  INTEGER, PARAMETER :: NVAR = 172 
! NFLUX - Number of Reaction Flux species
  INTEGER, PARAMETER :: NFLUX = 1 
! NFAM - Number of Prod/Loss Families
  INTEGER, PARAMETER :: NFAM = 6 
! NVARACT - Number of Active species
  INTEGER, PARAMETER :: NVARACT = 155 
! NFIX - Number of Fixed species
  INTEGER, PARAMETER :: NFIX = 6 
! NREACT - Number of reactions
  INTEGER, PARAMETER :: NREACT = 538 
! NVARST - Starting of variables in conc. vect.
  INTEGER, PARAMETER :: NVARST = 1 
! NFIXST - Starting of fixed in conc. vect.
  INTEGER, PARAMETER :: NFIXST = 173 
! NONZERO - Number of nonzero entries in Jacobian
  INTEGER, PARAMETER :: NONZERO = 2086 
! LU_NONZERO - Number of nonzero entries in LU factoriz. of Jacobian
  INTEGER, PARAMETER :: LU_NONZERO = 2603 
! CNVAR - (NVAR+1) Number of elements in compressed row format
  INTEGER, PARAMETER :: CNVAR = 173 
! NLOOKAT - Number of species to look at
  INTEGER, PARAMETER :: NLOOKAT = 0 
! NMONITOR - Number of species to monitor
  INTEGER, PARAMETER :: NMONITOR = 0 
! NMASS - Number of atoms to check mass balance
  INTEGER, PARAMETER :: NMASS = 1 

! Index declaration for variable species in C and VAR
!   VAR(ind_spc) = C(ind_spc)

  INTEGER, PARAMETER :: ind_MONX = 1 
  INTEGER, PARAMETER :: ind_MSA = 2 
  INTEGER, PARAMETER :: ind_LISOPOH = 3 
  INTEGER, PARAMETER :: ind_LISOPNO3 = 4 
  INTEGER, PARAMETER :: ind_LBRO2H = 5 
  INTEGER, PARAMETER :: ind_LBRO2N = 6 
  INTEGER, PARAMETER :: ind_LTRO2H = 7 
  INTEGER, PARAMETER :: ind_LTRO2N = 8 
  INTEGER, PARAMETER :: ind_LXRO2H = 9 
  INTEGER, PARAMETER :: ind_LXRO2N = 10 
  INTEGER, PARAMETER :: ind_PYAC = 11 
  INTEGER, PARAMETER :: ind_CO2 = 12 
  INTEGER, PARAMETER :: ind_POx = 13 
  INTEGER, PARAMETER :: ind_LOx = 14 
  INTEGER, PARAMETER :: ind_PCO = 15 
  INTEGER, PARAMETER :: ind_LCO = 16 
  INTEGER, PARAMETER :: ind_PSO4 = 17 
  INTEGER, PARAMETER :: ind_LCH4 = 18 
  INTEGER, PARAMETER :: ind_TOLU = 19 
  INTEGER, PARAMETER :: ind_XYLE = 20 
  INTEGER, PARAMETER :: ind_BENZ = 21 
  INTEGER, PARAMETER :: ind_CH3CCl3 = 22 
  INTEGER, PARAMETER :: ind_PPN = 23 
  INTEGER, PARAMETER :: ind_BrNO2 = 24 
  INTEGER, PARAMETER :: ind_IEPOX = 25 
  INTEGER, PARAMETER :: ind_PMNN = 26 
  INTEGER, PARAMETER :: ind_CCl4 = 27 
  INTEGER, PARAMETER :: ind_CFC11 = 28 
  INTEGER, PARAMETER :: ind_CFC12 = 29 
  INTEGER, PARAMETER :: ind_CFC113 = 30 
  INTEGER, PARAMETER :: ind_CFC114 = 31 
  INTEGER, PARAMETER :: ind_CFC115 = 32 
  INTEGER, PARAMETER :: ind_H1301 = 33 
  INTEGER, PARAMETER :: ind_H2402 = 34 
  INTEGER, PARAMETER :: ind_N2O = 35 
  INTEGER, PARAMETER :: ind_BRO2 = 36 
  INTEGER, PARAMETER :: ind_TRO2 = 37 
  INTEGER, PARAMETER :: ind_XRO2 = 38 
  INTEGER, PARAMETER :: ind_H1211 = 39 
  INTEGER, PARAMETER :: ind_N = 40 
  INTEGER, PARAMETER :: ind_PAN = 41 
  INTEGER, PARAMETER :: ind_OCS = 42 
  INTEGER, PARAMETER :: ind_ALK4 = 43 
  INTEGER, PARAMETER :: ind_MAP = 44 
  INTEGER, PARAMETER :: ind_CHBr3 = 45 
  INTEGER, PARAMETER :: ind_CH2Br2 = 46 
  INTEGER, PARAMETER :: ind_MPN = 47 
  INTEGER, PARAMETER :: ind_Cl2O2 = 48 
  INTEGER, PARAMETER :: ind_HNO2 = 49 
  INTEGER, PARAMETER :: ind_RA3P = 50 
  INTEGER, PARAMETER :: ind_RB3P = 51 
  INTEGER, PARAMETER :: ind_DMS = 52 
  INTEGER, PARAMETER :: ind_OClO = 53 
  INTEGER, PARAMETER :: ind_ClNO2 = 54 
  INTEGER, PARAMETER :: ind_HCFC22 = 55 
  INTEGER, PARAMETER :: ind_HCFC123 = 56 
  INTEGER, PARAMETER :: ind_HCFC141b = 57 
  INTEGER, PARAMETER :: ind_HCFC142b = 58 
  INTEGER, PARAMETER :: ind_C3H8 = 59 
  INTEGER, PARAMETER :: ind_ETP = 60 
  INTEGER, PARAMETER :: ind_CH3Br = 61 
  INTEGER, PARAMETER :: ind_CH3Cl = 62 
  INTEGER, PARAMETER :: ind_MAOP = 63 
  INTEGER, PARAMETER :: ind_HNO4 = 64 
  INTEGER, PARAMETER :: ind_ClOO = 65 
  INTEGER, PARAMETER :: ind_MP = 66 
  INTEGER, PARAMETER :: ind_RP = 67 
  INTEGER, PARAMETER :: ind_BrCl = 68 
  INTEGER, PARAMETER :: ind_PRPN = 69 
  INTEGER, PARAMETER :: ind_SO4 = 70 
  INTEGER, PARAMETER :: ind_Br2 = 71 
  INTEGER, PARAMETER :: ind_ETHLN = 72 
  INTEGER, PARAMETER :: ind_PP = 73 
  INTEGER, PARAMETER :: ind_R4P = 74 
  INTEGER, PARAMETER :: ind_RIP = 75 
  INTEGER, PARAMETER :: ind_VRP = 76 
  INTEGER, PARAMETER :: ind_ATOOH = 77 
  INTEGER, PARAMETER :: ind_IAP = 78 
  INTEGER, PARAMETER :: ind_C2H6 = 79 
  INTEGER, PARAMETER :: ind_DHMOB = 80 
  INTEGER, PARAMETER :: ind_MOBA = 81 
  INTEGER, PARAMETER :: ind_MRP = 82 
  INTEGER, PARAMETER :: ind_N2O5 = 83 
  INTEGER, PARAMETER :: ind_HCOOH = 84 
  INTEGER, PARAMETER :: ind_INPN = 85 
  INTEGER, PARAMETER :: ind_ISNP = 86 
  INTEGER, PARAMETER :: ind_ISOPNB = 87 
  INTEGER, PARAMETER :: ind_ROH = 88 
  INTEGER, PARAMETER :: ind_MOBAOO = 89 
  INTEGER, PARAMETER :: ind_DIBOO = 90 
  INTEGER, PARAMETER :: ind_IEPOXOO = 91 
  INTEGER, PARAMETER :: ind_PMN = 92 
  INTEGER, PARAMETER :: ind_BrNO3 = 93 
  INTEGER, PARAMETER :: ind_MACRNO2 = 94 
  INTEGER, PARAMETER :: ind_H = 95 
  INTEGER, PARAMETER :: ind_ISOP = 96 
  INTEGER, PARAMETER :: ind_PRPE = 97 
  INTEGER, PARAMETER :: ind_Cl2 = 98 
  INTEGER, PARAMETER :: ind_ISNOHOO = 99 
  INTEGER, PARAMETER :: ind_ISOPND = 100 
  INTEGER, PARAMETER :: ind_ISNOOB = 101 
  INTEGER, PARAMETER :: ind_MVKN = 102 
  INTEGER, PARAMETER :: ind_HOBr = 103 
  INTEGER, PARAMETER :: ind_PROPNN = 104 
  INTEGER, PARAMETER :: ind_GLYX = 105 
  INTEGER, PARAMETER :: ind_GAOO = 106 
  INTEGER, PARAMETER :: ind_CH4 = 107 
  INTEGER, PARAMETER :: ind_A3O2 = 108 
  INTEGER, PARAMETER :: ind_MVKOO = 109 
  INTEGER, PARAMETER :: ind_MGLYOO = 110 
  INTEGER, PARAMETER :: ind_MAOPO2 = 111 
  INTEGER, PARAMETER :: ind_ACET = 112 
  INTEGER, PARAMETER :: ind_MGLOO = 113 
  INTEGER, PARAMETER :: ind_CH2OO = 114 
  INTEGER, PARAMETER :: ind_ACTA = 115 
  INTEGER, PARAMETER :: ind_ISNOOA = 116 
  INTEGER, PARAMETER :: ind_PO2 = 117 
  INTEGER, PARAMETER :: ind_MACRN = 118 
  INTEGER, PARAMETER :: ind_CH3CHOO = 119 
  INTEGER, PARAMETER :: ind_H2O2 = 120 
  INTEGER, PARAMETER :: ind_MAN2 = 121 
  INTEGER, PARAMETER :: ind_PRN1 = 122 
  INTEGER, PARAMETER :: ind_KO2 = 123 
  INTEGER, PARAMETER :: ind_VRO2 = 124 
  INTEGER, PARAMETER :: ind_ClNO3 = 125 
  INTEGER, PARAMETER :: ind_B3O2 = 126 
  INTEGER, PARAMETER :: ind_HC5OO = 127 
  INTEGER, PARAMETER :: ind_ETO2 = 128 
  INTEGER, PARAMETER :: ind_RCO3 = 129 
  INTEGER, PARAMETER :: ind_MRO2 = 130 
  INTEGER, PARAMETER :: ind_HNO3 = 131 
  INTEGER, PARAMETER :: ind_HOCl = 132 
  INTEGER, PARAMETER :: ind_GLYC = 133 
  INTEGER, PARAMETER :: ind_R4N1 = 134 
  INTEGER, PARAMETER :: ind_ATO2 = 135 
  INTEGER, PARAMETER :: ind_ISN1 = 136 
  INTEGER, PARAMETER :: ind_MAO3 = 137 
  INTEGER, PARAMETER :: ind_RIO2 = 138 
  INTEGER, PARAMETER :: ind_INO2 = 139 
  INTEGER, PARAMETER :: ind_HC5 = 140 
  INTEGER, PARAMETER :: ind_MGLY = 141 
  INTEGER, PARAMETER :: ind_ISOPNBO2 = 142 
  INTEGER, PARAMETER :: ind_ISOPNDO2 = 143 
  INTEGER, PARAMETER :: ind_MACROO = 144 
  INTEGER, PARAMETER :: ind_R4O2 = 145 
  INTEGER, PARAMETER :: ind_HAC = 146 
  INTEGER, PARAMETER :: ind_R4N2 = 147 
  INTEGER, PARAMETER :: ind_BrO = 148 
  INTEGER, PARAMETER :: ind_RCHO = 149 
  INTEGER, PARAMETER :: ind_MEK = 150 
  INTEGER, PARAMETER :: ind_ClO = 151 
  INTEGER, PARAMETER :: ind_MACR = 152 
  INTEGER, PARAMETER :: ind_ALD2 = 153 
  INTEGER, PARAMETER :: ind_MVK = 154 
  INTEGER, PARAMETER :: ind_MCO3 = 155 
  INTEGER, PARAMETER :: ind_SO2 = 156 
  INTEGER, PARAMETER :: ind_CH2O = 157 
  INTEGER, PARAMETER :: ind_NO = 158 
  INTEGER, PARAMETER :: ind_HO2 = 159 
  INTEGER, PARAMETER :: ind_HBr = 160 
  INTEGER, PARAMETER :: ind_HCl = 161 
  INTEGER, PARAMETER :: ind_Cl = 162 
  INTEGER, PARAMETER :: ind_H2O = 163 
  INTEGER, PARAMETER :: ind_O1D = 164 
  INTEGER, PARAMETER :: ind_OH = 165 
  INTEGER, PARAMETER :: ind_O = 166 
  INTEGER, PARAMETER :: ind_CO = 167 
  INTEGER, PARAMETER :: ind_NO2 = 168 
  INTEGER, PARAMETER :: ind_O3 = 169 
  INTEGER, PARAMETER :: ind_NO3 = 170 
  INTEGER, PARAMETER :: ind_Br = 171 
  INTEGER, PARAMETER :: ind_MO2 = 172 

! Index declaration for fixed species in C
!   C(ind_spc)

  INTEGER, PARAMETER :: ind_EOH = 173 
  INTEGER, PARAMETER :: ind_H2 = 174 
  INTEGER, PARAMETER :: ind_MOH = 175 
  INTEGER, PARAMETER :: ind_N2 = 176 
  INTEGER, PARAMETER :: ind_O2 = 177 
  INTEGER, PARAMETER :: ind_RCOOH = 178 

! Index declaration for fixed species in FIX
!    FIX(indf_spc) = C(ind_spc) = C(NVAR+indf_spc)

  INTEGER, PARAMETER :: indf_EOH = 1 
  INTEGER, PARAMETER :: indf_H2 = 2 
  INTEGER, PARAMETER :: indf_MOH = 3 
  INTEGER, PARAMETER :: indf_N2 = 4 
  INTEGER, PARAMETER :: indf_O2 = 5 
  INTEGER, PARAMETER :: indf_RCOOH = 6 

END MODULE gckpp_Parameters

