! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Utility Data Module File
! 
! Generated by KPP-2.2.4_gc symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : gckpp_Monitor.f90
! Time                 : Wed Aug 23 13:23:46 2017
! Working directory    : /n/home05/msulprizio/GC/FlexChem/Mechanisms/v11-02c/SOA_SVPOA
! Equation file        : gckpp.kpp
! Output root filename : gckpp
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE gckpp_Monitor


  CHARACTER(LEN=15), PARAMETER, DIMENSION(90) :: SPC_NAMES_0 = (/ &
     'MONX           ','CO2            ','INDIOL         ', & ! index 1 - 3
     'ISN1OA         ','ISN1OG         ','LBRO2H         ', & ! index 4 - 6
     'LBRO2N         ','LISOPOH        ','LISOPNO3       ', & ! index 7 - 9
     'LNRO2H         ','LNRO2N         ','NRO2           ', & ! index 10 - 12
     'NAP            ','LTRO2H         ','LTRO2N         ', & ! index 13 - 15
     'LVOCOA         ','LVOC           ','LXRO2H         ', & ! index 16 - 18
     'LXRO2N         ','MSA            ','PYAC           ', & ! index 19 - 21
     'SO4            ','SOAGX          ','SOAIE          ', & ! index 22 - 24
     'SOAME          ','IMAE           ','SOAMG          ', & ! index 25 - 27
     'POx            ','LOx            ','PCO            ', & ! index 28 - 30
     'LCO            ','PSO4           ','CH2Br2         ', & ! index 31 - 33
     'CH3Br          ','CHBr3          ','DHDC           ', & ! index 34 - 36
     'MONITA         ','BENZ           ','DHDN           ', & ! index 37 - 39
     'PMNN           ','PPN            ','TOLU           ', & ! index 40 - 42
     'BrNO2          ','IEPOXD         ','N2O5           ', & ! index 43 - 45
     'BRO2           ','TRO2           ','IEPOXA         ', & ! index 46 - 48
     'IEPOXB         ','IONITA         ','ALK4           ', & ! index 49 - 51
     'XRO2           ','MAP            ','HNO2           ', & ! index 52 - 54
     'IMAO3          ','C3H8           ','MPN            ', & ! index 55 - 57
     'MP             ','RA3P           ','RB3P           ', & ! index 58 - 60
     'HNO4           ','XYLE           ','ETP            ', & ! index 61 - 63
     'DMS            ','HOBr           ','Br2            ', & ! index 64 - 66
     'HBr            ','C2H6           ','EOH            ', & ! index 67 - 69
     'PAN            ','RP             ','PP             ', & ! index 70 - 72
     'PRPN           ','BrNO3          ','PIP            ', & ! index 73 - 75
     'R4P            ','HPALD          ','ATOOH          ', & ! index 76 - 78
     'DHPCARP        ','IAP            ','MRP            ', & ! index 79 - 81
     'HC187          ','RIPB           ','VRP            ', & ! index 82 - 84
     'HPC52O2        ','H2O2           ','MOBA           ', & ! index 85 - 87
     'HONIT          ','DHMOB          ','RIPA           ' /)
  CHARACTER(LEN=15), PARAMETER, DIMENSION(90) :: SPC_NAMES_1 = (/ &
     'RIPD           ','HCOOH          ','ISNP           ', & ! index 91 - 93
     'MAOP           ','ETHLN          ','MTPA           ', & ! index 94 - 96
     'INPN           ','NPMN           ','LIMO           ', & ! index 97 - 99
     'MOBAOO         ','DIBOO          ','MACRNO2        ', & ! index 100 - 102
     'IPMN           ','MVKOO          ','ACTA           ', & ! index 103 - 105
     'ROH            ','ISOPNB         ','MONITS         ', & ! index 106 - 108
     'CH3CHOO        ','GAOO           ','BrO            ', & ! index 109 - 111
     'MGLYOO         ','CH2OO          ','ISOP           ', & ! index 112 - 114
     'PO2            ','ACET           ','ISNOHOO        ', & ! index 115 - 117
     'MGLOO          ','A3O2           ','ISNOOB         ', & ! index 118 - 120
     'IEPOXOO        ','PRN1           ','MVKN           ', & ! index 121 - 123
     'GLYX           ','MACROO         ','MONITU         ', & ! index 124 - 126
     'PROPNN         ','MAN2           ','ISNOOA         ', & ! index 127 - 129
     'ISOPNDO2       ','HNO3           ','MACRN          ', & ! index 130 - 132
     'ISOPNBO2       ','MAOPO2         ','B3O2           ', & ! index 133 - 135
     'ATO2           ','GLYC           ','ISOPND         ', & ! index 136 - 138
     'VRO2           ','R4N1           ','OLND           ', & ! index 139 - 141
     'OLNN           ','ETO2           ','RCO3           ', & ! index 142 - 144
     'KO2            ','LIMO2          ','HC5OO          ', & ! index 145 - 147
     'PIO2           ','NMAO3          ','ISN1           ', & ! index 148 - 150
     'PRPE           ','MGLY           ','MRO2           ', & ! index 151 - 153
     'CH2O           ','INO2           ','HC5            ', & ! index 154 - 156
     'R4O2           ','RIO2           ','R4N2           ', & ! index 157 - 159
     'HAC            ','ALD2           ','MVK            ', & ! index 160 - 162
     'MEK            ','RCHO           ','Br             ', & ! index 163 - 165
     'OH             ','HO2            ','NO             ', & ! index 166 - 168
     'CO             ','O3             ','NO3            ', & ! index 169 - 171
     'MACR           ','NO2            ','MO2            ', & ! index 172 - 174
     'MCO3           ','SO2            ','CH4            ', & ! index 175 - 177
     'H2             ','H2O            ','MOH            ' /)
  CHARACTER(LEN=15), PARAMETER, DIMENSION(2) :: SPC_NAMES_2 = (/ &
     'O2             ','RCOOH          ' /)
  CHARACTER(LEN=15), PARAMETER, DIMENSION(182) :: SPC_NAMES = (/&
    SPC_NAMES_0, SPC_NAMES_1, SPC_NAMES_2 /)

  INTEGER, DIMENSION(1) :: LOOKAT
  INTEGER, DIMENSION(1) :: MONITOR
  CHARACTER(LEN=15), DIMENSION(1) :: SMASS
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_0 = (/ &
     '       NO + O3 --> NO2 + O2                                                                         ', & ! index 1
     '       OH + O3 --> LOx + HO2 + O2                                                                   ', & ! index 2
     '      HO2 + O3 --> LOx + OH + 2 O2                                                                  ', & ! index 3
     '      O3 + NO2 --> NO3 + O2                                                                         ', & ! index 4
     '      O3 + MO2 --> LOx + CH2O + HO2 + 2 O2                                                          ', & ! index 5
     '          2 OH --> POx + O3 + H2O                                                                   ', & ! index 6
     '          2 OH --> H2O2                                                                             ', & ! index 7
     '      OH + HO2 --> H2O + O2                                                                         ', & ! index 8
     '     H2O2 + OH --> HO2 + H2O                                                                        ', & ! index 9
     '      HO2 + NO --> POx + OH + NO2                                                                   ', & ! index 10
     '         2 HO2 --> H2O2                                                                             ', & ! index 11
     '       OH + H2 --> HO2 + H2O                                                                        ', & ! index 12
     '       OH + CO --> CO2 + LCO + HO2                                                                  ', & ! index 13
     '      OH + CH4 --> MO2 + H2O                                                                        ', & ! index 14
     '      NO + MO2 --> POx + CH2O + HO2 + NO2                                                           ', & ! index 15
     '     HO2 + MO2 --> MP + O2                                                                          ', & ! index 16
     '         2 MO2 --> CH2O + MOH + O2                                                                  ', & ! index 17
     '         2 MO2 --> 2 CH2O + 2 HO2                                                                   ', & ! index 18
     '       MP + OH --> MO2 + H2O                                                                        ', & ! index 19
     '       MP + OH --> CH2O + OH + H2O                                                                  ', & ! index 20
     '    ATOOH + OH --> ATO2 + H2O                                                                       ', & ! index 21
     '    ATOOH + OH --> MGLY + OH + H2O                                                                  ', & ! index 22
     '     CH2O + OH --> PCO + HO2 + CO + H2O                                                             ', & ! index 23
     '      OH + NO2 --> HNO3                                                                             ', & ! index 24
     '     HNO3 + OH --> POx + NO3 + H2O                                                                  ', & ! index 25
     '       OH + NO --> HNO2                                                                             ', & ! index 26
     '     HNO2 + OH --> POx + NO2 + H2O                                                                  ', & ! index 27
     '     HO2 + NO2 --> HNO4                                                                             ', & ! index 28
     '          HNO4 --> HO2 + NO2                                                                        ', & ! index 29
     '     HNO4 + OH --> NO2 + H2O + O2                                                                   ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_1 = (/ &
     '     HO2 + NO3 --> LOx + OH + NO2 + O2                                                              ', & ! index 31
     '      NO + NO3 --> 2 NO2                                                                            ', & ! index 32
     '      OH + NO3 --> LOx + HO2 + NO2                                                                  ', & ! index 33
     '     NO3 + NO2 --> N2O5                                                                             ', & ! index 34
     '          N2O5 --> NO3 + NO2                                                                        ', & ! index 35
     '    HCOOH + OH --> CO2 + HO2 + H2O                                                                  ', & ! index 36
     '      OH + MOH --> CH2O + HO2                                                                       ', & ! index 37
     '     NO3 + NO2 --> 2 LOx + NO + NO2 + O2                                                            ', & ! index 38
     '    CH2O + NO3 --> LOx + PCO + HNO3 + HO2 + CO                                                      ', & ! index 39
     '     ALD2 + OH --> 0.05 PCO + 0.05 CH2O + 0.05 HO2 + 0.05 CO + 0.95 MCO3                            ', & ! index 40
     '    ALD2 + NO3 --> LOx + HNO3 + MCO3                                                                ', & ! index 41
     '    NO2 + MCO3 --> PAN                                                                              ', & ! index 42
     '           PAN --> NO2 + MCO3                                                                       ', & ! index 43
     '     NO + MCO3 --> CO2 + POx + NO2 + MO2                                                            ', & ! index 44
     '     C2H6 + OH --> ETO2 + H2O                                                                       ', & ! index 45
     '     ETO2 + NO --> POx + ALD2 + HO2 + NO2                                                           ', & ! index 46
     '     C3H8 + OH --> B3O2                                                                             ', & ! index 47
     '     C3H8 + OH --> A3O2                                                                             ', & ! index 48
     '     A3O2 + NO --> POx + RCHO + HO2 + NO2                                                           ', & ! index 49
     '      PO2 + NO --> POx + CH2O + ALD2 + HO2 + NO2                                                    ', & ! index 50
     '     ALK4 + OH --> R4O2                                                                             ', & ! index 51
     '     R4O2 + NO --> POx + 0.32 ACET + 0.05 A3O2 + 0.18 B3O2 + 0.32 ETO2 + 0.32 ALD2 + 0.19 MEK + 0.14', & ! index 52
     '     R4O2 + NO --> POx + R4N2                                                                       ', & ! index 53
     '     R4N1 + NO --> POx + 0.57 CH2O + 0.86 ALD2 + 0.57 RCHO + 2 NO2                                  ', & ! index 54
     '     ATO2 + NO --> POx + CH2O + NO2 + MCO3                                                          ', & ! index 55
     '      KO2 + NO --> POx + 0.07 R4N2 + 0.93 ALD2 + 0.93 NO2 + 0.93 MCO3                               ', & ! index 56
     '     RIO2 + NO --> POx + 0.03 DIBOO + 0.081 ISOPNB + 0.009 ISOPND + 0.82 CH2O + 0.058 HC5 + 0.476 MV', & ! index 57
     '          RIO2 --> 0.5 HPALD + 0.5 DHPCARP                                                          ', & ! index 58
     '     VRO2 + NO --> POx + 0.12 MVKN + 0.53 GLYC + 0.35 MGLY + 0.35 CH2O + 0.35 HO2 + 0.88 NO2 + 0.53 ', & ! index 59
     '     MRO2 + NO --> POx + 0.728 PCO + 0.15 MACRN + 0.122 MGLY + 0.122 CH2O + 0.728 HAC + 0.85 HO2 + 0' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_2 = (/ &
     '          MRO2 --> PCO + HAC + OH + CO                                                              ', & ! index 61
     '     MAN2 + NO --> POx + 0.5 PCO + 0.5 PROPNN + 0.5 MGLY + 0.5 CH2O + 0.5 OH + 0.5 CO + 1.5 NO2     ', & ! index 62
     '     B3O2 + NO --> POx + ACET + HO2 + NO2                                                           ', & ! index 63
     '     INO2 + NO --> POx + 0.7 ISN1 + 0.07 CH2O + 0.23 HC5 + 0.035 MVK + 0.8 HO2 + 0.035 MACR + 1.3 NO', & ! index 64
     '    INO2 + NO3 --> LOx + 0.7 ISN1 + 0.07 CH2O + 0.23 HC5 + 0.035 MVK + 0.8 HO2 + 0.035 MACR + 1.3 NO', & ! index 65
     '    ISN1 + NO3 --> 1.4 LOx + 0.4 ISNOOB + 0.6 ISNOOA + 0.6 HNO3                                     ', & ! index 66
     '  ISNOOA + NO3 --> 0.04 ISN1OG + 1.04 LOx + PCO + 0.96 PROPNN + HO2 + CO + NO2                      ', & ! index 67
     '   ISNOOA + NO --> 0.04 ISN1OG + 0.96 POx + PCO + 0.96 PROPNN + HO2 + CO + NO2                      ', & ! index 68
     '  ISNOOA + NO2 --> 0.04 ISN1OG + 2 LOx + 0.96 IPMN                                                  ', & ! index 69
     '  ISNOOA + HO2 --> 0.04 ISN1OG + 0.21 POx + 0.75 RP + 0.25 O3 + 0.96 NO2 + 0.25 RCOOH               ', & ! index 70
     '  ISNOOB + NO3 --> 0.04 ISN1OG + 0.06 LOx + GLYX + 0.94 PROPNN + 2 NO2                              ', & ! index 71
     '   ISNOOB + NO --> 0.04 ISN1OG + 1.78 POx + 0.94 GLYX + 0.9 PROPNN + 1.88 NO2                       ', & ! index 72
     '  ISNOOB + HO2 --> 0.04 ISN1OG + 0.04 LOx + 0.96 INPN                                               ', & ! index 73
     '  ISNOOB + MO2 --> 0.04 ISN1OG + 0.36 POx + 0.7 GLYX + 0.66 PROPNN + 0.75 CH2O + 0.5 HO2 + 0.7 NO2 +', & ! index 74
     '     ISN1 + O3 --> LOx + 0.7 GLYX + 0.3 PROPNN + 0.75 CH2O + 0.5 HO2 + 0.7 NO2 + 0.25 MOH           ', & ! index 75
     '     ISN1 + OH --> 0.655 ISNOHOO + 0.345 ISNOOA                                                     ', & ! index 76
     '  ISNOHOO + NO --> 0.04 ISN1OG + 0.106 LOx + 0.919 GLYX + 0.894 PROPNN + 0.934 HO2                  ', & ! index 77
     ' ISNOHOO + HO2 --> 0.04 ISN1OG + 0.04 LOx + 0.96 INPN                                               ', & ! index 78
     ' ISNOHOO + MO2 --> 0.04 ISN1OG + 0.34 LOx + 0.7 GLYX + 0.66 PROPNN + 0.75 CH2O + 1.2 HO2 + 0.25 MOH ', & ! index 79
     '        2 INO2 --> 0.5 ISOPND + 1.2 ISN1 + 0.07 CH2O + 0.23 HC5 + 0.035 MVK + 0.8 HO2 + 0.035 MACR +', & ! index 80
     '     PRN1 + NO --> POx + CH2O + ALD2 + 2 NO2                                                        ', & ! index 81
     '    ALK4 + NO3 --> LOx + HNO3 + R4O2                                                                ', & ! index 82
     '     R4N2 + OH --> R4N1 + H2O                                                                       ', & ! index 83
     '     ACTA + OH --> CO2 + MO2 + H2O                                                                  ', & ! index 84
     '     RCHO + OH --> RCO3 + H2O                                                                       ', & ! index 85
     '    RCO3 + NO2 --> PPN                                                                              ', & ! index 86
     '           PPN --> RCO3 + NO2                                                                       ', & ! index 87
     '   IMAO3 + NO2 --> LOx + IPMN                                                                       ', & ! index 88
     '   NMAO3 + NO2 --> NPMN                                                                             ', & ! index 89
     '          IPMN --> POx + IMAO3 + NO2                                                                ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_3 = (/ &
     '          NPMN --> NMAO3 + NO2                                                                      ', & ! index 91
     '     RCO3 + NO --> POx + ETO2 + NO2                                                                 ', & ! index 92
     '    NMAO3 + NO --> CO2 + POx + 0.5 PCO + 0.5 CH2O + 0.5 CO + NO2 + 0.5 MO2 + 0.5 MCO3               ', & ! index 93
     '    RCHO + NO3 --> LOx + HNO3 + RCO3                                                                ', & ! index 94
     '     ACET + OH --> ATO2 + H2O                                                                       ', & ! index 95
     '    A3O2 + MO2 --> 0.25 ROH + 0.75 CH2O + 0.75 RCHO + HO2 + 0.25 MOH                                ', & ! index 96
     '     PO2 + MO2 --> 0.25 ROH + 1.25 CH2O + 0.16 HAC + 0.5 ALD2 + 0.09 RCHO + HO2 + 0.25 MOH          ', & ! index 97
     '    R4O2 + HO2 --> R4P                                                                              ', & ! index 98
     '    R4N1 + HO2 --> R4N2                                                                             ', & ! index 99
     '    ATO2 + HO2 --> 0.85 ATOOH + 0.15 CH2O + 0.15 OH + 0.15 MCO3                                     ', & ! index 100
     '     KO2 + HO2 --> 0.85 ATOOH + 0.15 ALD2 + 0.15 OH + 0.15 MCO3                                     ', & ! index 101
     '    RIO2 + HO2 --> 0.272 RIPB + 0.628 RIPA + 0.037 RIPD + 0.063 CH2O + 0.038 MVK + 0.063 OH + 0.063 ', & ! index 102
     '    VRO2 + HO2 --> 0.1 VRP + 0.578 GLYC + 0.102 MGLY + 0.102 CH2O + 0.187 MEK + 0.033 RCHO + 0.68 OH', & ! index 103
     '    MRO2 + HO2 --> MRP                                                                              ', & ! index 104
     '    MAN2 + HO2 --> 0.075 PCO + 0.85 MAOP + 0.075 PROPNN + 0.075 MGLY + 0.075 CH2O + 0.15 OH + 0.075 ', & ! index 105
     '    B3O2 + HO2 --> RB3P                                                                             ', & ! index 106
     '    INO2 + HO2 --> INPN                                                                             ', & ! index 107
     '    PRN1 + HO2 --> PRPN                                                                             ', & ! index 108
     '      MEK + OH --> KO2 + H2O                                                                        ', & ! index 109
     '    ETO2 + MO2 --> 0.25 EOH + 0.75 CH2O + 0.75 ALD2 + HO2 + 0.25 MOH                                ', & ! index 110
     '     MEK + NO3 --> LOx + HNO3 + KO2                                                                 ', & ! index 111
     '    R4O2 + MO2 --> 0.25 ROH + 0.16 ACET + 0.03 A3O2 + 0.09 B3O2 + 0.16 ETO2 + 0.75 CH2O + 0.16 ALD2 ', & ! index 112
     '    R4N1 + MO2 --> 0.25 ROH + 0.95 CH2O + 0.15 R4O2 + 0.38 ALD2 + 0.54 RCHO + 0.5 HO2 + NO2 + 0.25 M', & ! index 113
     '    ATO2 + MO2 --> 0.5 MGLY + 0.5 CH2O + 0.2 HAC + 0.3 HO2 + 0.3 MCO3 + 0.5 MOH                     ', & ! index 114
     '     KO2 + MO2 --> 0.25 ROH + 0.75 CH2O + 0.5 ALD2 + 0.25 MEK + 0.5 HO2 + 0.5 MCO3 + 0.25 MOH       ', & ! index 115
     '    RIO2 + MO2 --> 0.24 ROH + 1.22 CH2O + 0.3 HC5 + 0.28 MVK + 1.1 HO2 + 0.18 MACR + 0.24 MOH       ', & ! index 116
     '        2 RIO2 --> 0.29 PCO + 0.09 DIBOO + 0.75 CH2O + 1.11 HC5 + 0.45 MVK + 0.91 HO2 + 0.29 CO + 0.', & ! index 117
     '   HC5OO + MO2 --> 0.33 PCO + 0.25 ROH + 0.13 GLYC + 0.29 MGLY + 0.95 CH2O + 0.18 HAC + 0.25 MEK + H', & ! index 118
     '    VRO2 + MO2 --> 0.25 ROH + 0.36 GLYC + 0.14 MGLY + 0.89 CH2O + 0.25 MEK + 0.64 HO2 + 0.36 MCO3 + ', & ! index 119
     '    MRO2 + MO2 --> 0.595 PCO + 0.15 ROH + 0.255 MGLY + 1.255 CH2O + 0.595 HAC + 1.7 HO2 + 0.595 CO  ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_4 = (/ &
     '    MAN2 + MO2 --> 0.375 PCO + 0.375 PROPNN + 0.375 MGLY + 0.625 CH2O + 0.25 R4N2 + 0.375 HO2 + 0.37', & ! index 121
     '    B3O2 + MO2 --> 0.25 ROH + 0.75 ACET + 0.75 CH2O + HO2 + 0.25 MOH                                ', & ! index 122
     '    INO2 + MO2 --> 0.25 ISOPND + 0.6 ISN1 + 0.785 CH2O + 0.115 HC5 + 0.018 MVK + 0.9 HO2 + 0.018 MAC', & ! index 123
     '    PRN1 + MO2 --> 0.25 ROH + 1.25 CH2O + 0.5 ALD2 + 0.25 RCHO + 0.5 HO2 + NO2 + 0.25 MOH           ', & ! index 124
     '      EOH + OH --> ALD2 + HO2                                                                       ', & ! index 125
     '      ROH + OH --> RCHO + HO2                                                                       ', & ! index 126
     '        2 ETO2 --> 2 ALD2 + 2 HO2                                                                   ', & ! index 127
     '        2 ETO2 --> EOH + ALD2                                                                       ', & ! index 128
     '    ETO2 + HO2 --> ETP                                                                              ', & ! index 129
     '    A3O2 + HO2 --> RA3P                                                                             ', & ! index 130
     '     PO2 + HO2 --> PP                                                                               ', & ! index 131
     '    HO2 + MCO3 --> 0.15 POx + 0.41 MAP + 0.15 ACTA + 0.44 OH + 0.15 O3 + 0.44 MO2                   ', & ! index 132
     '    RCO3 + HO2 --> 0.15 POx + 0.41 RP + 0.44 ETO2 + 0.44 OH + 0.15 O3 + 0.15 RCOOH                  ', & ! index 133
     '   NMAO3 + HO2 --> 0.15 POx + 0.39 PCO + 0.41 MAOP + 0.59 CH2O + 0.44 OH + 0.39 CO + 0.15 O3 + 0.39 ', & ! index 134
     '     PRPE + OH --> PO2                                                                              ', & ! index 135
     '     PRPE + O3 --> LOx + 0.56 PCO + 0.12 CH3CHOO + 0.12 CH2OO + 0.5 CH2O + 0.5 ALD2 + 0.36 OH + 0.28', & ! index 136
     '     NPMN + OH --> PCO + HAC + CO + NO2                                                             ', & ! index 137
     '     IPMN + OH --> 0.781 IMAE + 1.81 POx + 0.03 PCO + 0.19 PAN + 0.19 CH2O + 0.03 HAC + 0.19 HO2 + 0', & ! index 138
     '     NPMN + O3 --> CH2O + NO3 + MCO3                                                                ', & ! index 139
     '     IMAE + OH --> OH                                                                               ', & ! index 140
     '     GLYC + OH --> 0.361 CO2 + 0.505 PCO + 0.134 HCOOH + 0.134 GLYX + 0.732 CH2O + 0.227 OH + 0.773 ', & ! index 141
     '     GLYC + OH --> PCO + HCOOH + OH + CO                                                            ', & ! index 142
     '    PRPE + NO3 --> LOx + PRN1                                                                       ', & ! index 143
     '     GLYX + OH --> 2 PCO + HO2 + 2 CO                                                               ', & ! index 144
     '     MGLY + OH --> PCO + CO + MCO3                                                                  ', & ! index 145
     '    GLYX + NO3 --> LOx + 2 PCO + HNO3 + HO2 + 2 CO                                                  ', & ! index 146
     '    MGLY + NO3 --> LOx + PCO + HNO3 + CO + MCO3                                                     ', & ! index 147
     '     ISOP + OH --> LISOPOH + RIO2                                                                   ', & ! index 148
     '      MVK + OH --> VRO2                                                                             ', & ! index 149
     '     OH + MACR --> 0.53 IMAO3 + 0.47 MRO2                                                           ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_5 = (/ &
     '      HAC + OH --> MGLY + HO2                                                                       ', & ! index 151
     '      HAC + OH --> 0.5 CO2 + 0.5 PCO + 0.5 HCOOH + 0.5 ACTA + OH + 0.5 CO + 0.5 MO2                 ', & ! index 152
     '   A3O2 + MCO3 --> RCHO + HO2 + MO2                                                                 ', & ! index 153
     '    PO2 + MCO3 --> CH2O + ALD2 + HO2 + MO2                                                          ', & ! index 154
     '   A3O2 + MCO3 --> ACTA + RCHO                                                                      ', & ! index 155
     '    PO2 + MCO3 --> ACTA + 0.65 HAC + 0.35 RCHO                                                      ', & ! index 156
     '     ISOP + O3 --> LOx + 0.495 PCO + 0.044 MVKOO + 0.11 CH2OO + 0.044 MACROO + 0.054 VRO2 + 0.102 PR', & ! index 157
     '      MVK + O3 --> LOx + 0.56 PCO + 0.12 CH2OO + 0.12 MGLOO + 0.5 MGLY + 0.6 CH2O + 0.1 ALD2 + 0.36 ', & ! index 158
     '     O3 + MACR --> LOx + 0.625 PCO + 0.022 MGLYOO + 0.326 CH2OO + 0.88 MGLY + 0.12 CH2O + 0.239 OH +', & ! index 159
     '    ISOP + NO3 --> LISOPNO3 + LOx + INO2                                                            ', & ! index 160
     '    NO3 + MACR --> LOx + MAN2                                                                       ', & ! index 161
     '    NO3 + MACR --> 1.5 LOx + 0.5 PCO + 0.5 IMAO3 + 0.5 MAOP + 0.5 HNO3 + 0.5 MRO2 + 0.5 HO2 + 0.5 CO', & ! index 162
     '    RCO3 + MO2 --> ETO2 + CH2O + HO2                                                                ', & ! index 163
     '   NMAO3 + MO2 --> 2 CH2O + HO2 + MCO3                                                              ', & ! index 164
     '    RCO3 + MO2 --> CH2O + RCOOH                                                                     ', & ! index 165
     '   NMAO3 + MO2 --> CH2O + RCOOH                                                                     ', & ! index 166
     '     INPN + OH --> MEK + OH + NO2                                                                   ', & ! index 167
     '     INPN + OH --> 0.36 INO2 + 0.64 R4N2 + 0.64 OH                                                  ', & ! index 168
     '     PRPN + OH --> 0.209 PRN1 + 0.791 PROPNN + 0.791 OH                                             ', & ! index 169
     '      ETP + OH --> 0.36 ETO2 + 0.64 ALD2 + 0.64 OH                                                  ', & ! index 170
     '     RA3P + OH --> 0.36 A3O2 + 0.64 RCHO + 0.64 OH                                                  ', & ! index 171
     '     RB3P + OH --> 0.791 ACET + 0.209 B3O2 + 0.791 OH                                               ', & ! index 172
     '      R4P + OH --> 0.209 R4O2 + 0.791 RCHO + 0.791 OH                                               ', & ! index 173
     '       RP + OH --> RCO3                                                                             ', & ! index 174
     '       PP + OH --> 0.209 PO2 + 0.791 HAC + 0.791 OH                                                 ', & ! index 175
     '     RIPA + OH --> 0.005 LVOC + 0.245 HC5 + 0.75 RIO2 + 0.125 OH + 0.125 H2O                        ', & ! index 176
     '     RIPB + OH --> 0.005 LVOC + 0.515 HC5 + 0.48 RIO2 + 0.26 OH + 0.26 H2O                          ', & ! index 177
     '     RIPD + OH --> 0.005 LVOC + 0.745 HC5 + 0.25 RIO2 + 0.375 OH + 0.375 H2O                        ', & ! index 178
     '     RIPA + OH --> 0.005 LVOC + 0.578 IEPOXA + 0.272 IEPOXB + 0.145 HC5OO + 0.85 OH                 ', & ! index 179
     '     RIPB + OH --> 0.68 IEPOXA + 0.32 IEPOXB + OH                                                   ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_6 = (/ &
     '     RIPD + OH --> 0.005 LVOC + 0.5 IEPOXD + 0.495 HC5OO + 0.5 OH                                   ', & ! index 181
     '     LVOC + OH --> OH                                                                               ', & ! index 182
     '   IEPOXA + OH --> IEPOXOO                                                                          ', & ! index 183
     '   IEPOXB + OH --> IEPOXOO                                                                          ', & ! index 184
     '   IEPOXD + OH --> IEPOXOO                                                                          ', & ! index 185
     ' IEPOXOO + HO2 --> 1.172 CO2 + 0.6 PCO + 0.44 HC187 + 0.278 HCOOH + 0.085 GLYX + 0.025 GLYC + 0.085 ', & ! index 186
     '  IEPOXOO + NO --> 0.858 CO2 + POx + 0.678 PCO + 0.473 HC187 + 0.142 HCOOH + 0.088 GLYX + 0.088 GLYC', & ! index 187
     '      IAP + OH --> 0.654 DHMOB + 0.346 HC5OO + 0.654 OH                                             ', & ! index 188
     '      VRP + OH --> 0.209 VRO2 + 0.791 MEK + 0.791 OH                                                ', & ! index 189
     '      MRP + OH --> MRO2                                                                             ', & ! index 190
     '      MRP + OH --> CO2 + HAC + OH                                                                   ', & ! index 191
     '     MAOP + OH --> NMAO3                                                                            ', & ! index 192
     '     MAOP + OH --> MAOPO2                                                                           ', & ! index 193
     ' MAOPO2 + MCO3 --> 2 CO2 + HAC + OH + MO2                                                           ', & ! index 194
     ' MAOPO2 + MCO3 --> ACTA + MEK                                                                       ', & ! index 195
     '  MAOPO2 + MO2 --> 0.7 CO2 + 0.3 ROH + CH2O + 0.7 HAC + 0.7 OH + 0.7 HO2                            ', & ! index 196
     '      2 MAOPO2 --> 2 CO2 + 2 HAC + 2 OH                                                             ', & ! index 197
     '  MAOPO2 + HO2 --> CO2 + HAC + 2 OH                                                                 ', & ! index 198
     '   MAOPO2 + NO --> CO2 + POx + HAC + OH + NO2                                                       ', & ! index 199
     '   MAOPO2 + NO --> POx + HNO3                                                                       ', & ! index 200
     '      MAP + OH --> MCO3                                                                             ', & ! index 201
     '    C2H6 + NO3 --> LOx + HNO3 + ETO2                                                                ', & ! index 202
     '      HC5 + O3 --> LOx + 0.89 PCO + 0.055 GAOO + 0.055 MGLYOO + 0.5 GLYC + 0.5 MGLY + 0.445 CH2O + 0', & ! index 203
     '        2 MCO3 --> 2 MO2                                                                            ', & ! index 204
     '    MO2 + MCO3 --> CH2O + HO2 + MO2                                                                 ', & ! index 205
     '    MO2 + MCO3 --> ACTA + CH2O                                                                      ', & ! index 206
     '   R4O2 + MCO3 --> 0.32 ACET + 0.05 A3O2 + 0.18 B3O2 + 0.32 ETO2 + 0.32 ALD2 + 0.19 MEK + 0.13 RCHO ', & ! index 207
     '   ATO2 + MCO3 --> CH2O + MO2 + MCO3                                                                ', & ! index 208
     '    KO2 + MCO3 --> ALD2 + MO2 + MCO3                                                                ', & ! index 209
     '   RIO2 + MCO3 --> CO2 + 0.113 DIBOO + 0.747 CH2O + 0.14 HC5 + 0.453 MVK + 0.887 HO2 + 0.294 MACR + ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_7 = (/ &
     '  HC5OO + MCO3 --> 0.09 PCO + 0.17 MOBA + 0.29 DHMOB + 0.216 GLYX + 0.234 GLYC + 0.234 MGLY + 0.216 ', & ! index 211
     '   VRO2 + MCO3 --> 0.6 GLYC + 0.4 MGLY + 0.4 CH2O + 0.4 HO2 + MO2 + 0.6 MCO3                        ', & ! index 212
     '   MRO2 + MCO3 --> 0.857 PCO + 0.143 MGLY + 0.143 CH2O + 0.857 HAC + 0.85 HO2 + 0.857 CO + MO2      ', & ! index 213
     '   B3O2 + MCO3 --> ACET + HO2 + MO2                                                                 ', & ! index 214
     '   R4N1 + MCO3 --> 0.39 CH2O + 0.3 R4O2 + 0.75 ALD2 + 0.57 RCHO + NO2 + MO2                         ', & ! index 215
     '   MAN2 + MCO3 --> CO2 + 0.5 PCO + 0.5 PROPNN + 0.5 MGLY + 0.5 CH2O + 0.5 HO2 + 0.5 CO + 0.5 NO2 + M', & ! index 216
     '   INO2 + MCO3 --> 0.7 ISN1 + 0.07 CH2O + 0.23 HC5 + 0.035 MVK + 0.8 HO2 + 0.035 MACR + 0.3 NO2 + MO', & ! index 217
     '   PRN1 + MCO3 --> CH2O + ALD2 + NO2 + MO2                                                          ', & ! index 218
     '   R4O2 + MCO3 --> ACTA + MEK                                                                       ', & ! index 219
     '   ATO2 + MCO3 --> ACTA + MGLY                                                                      ', & ! index 220
     '    KO2 + MCO3 --> ACTA + MEK                                                                       ', & ! index 221
     '   RIO2 + MCO3 --> ACTA + MEK                                                                       ', & ! index 222
     '  HC5OO + MCO3 --> ACTA + MEK                                                                       ', & ! index 223
     '   VRO2 + MCO3 --> ACTA + MEK                                                                       ', & ! index 224
     '   MRO2 + MCO3 --> ACTA + MEK                                                                       ', & ! index 225
     '   R4N1 + MCO3 --> ACTA + RCHO + NO2                                                                ', & ! index 226
     '   MAN2 + MCO3 --> ACTA + RCHO + NO2                                                                ', & ! index 227
     '   INO2 + MCO3 --> ACTA + RCHO + NO2                                                                ', & ! index 228
     '   PRN1 + MCO3 --> ACTA + RCHO + NO2                                                                ', & ! index 229
     '   B3O2 + MCO3 --> ACTA + ACET                                                                      ', & ! index 230
     '   ETO2 + MCO3 --> ALD2 + HO2 + MO2                                                                 ', & ! index 231
     '   ETO2 + MCO3 --> ACTA + ALD2                                                                      ', & ! index 232
     '   RCO3 + MCO3 --> ETO2 + MO2                                                                       ', & ! index 233
     '  NMAO3 + MCO3 --> CH2O + MO2 + MCO3                                                                ', & ! index 234
     '         2 NO3 --> 2 LOx + 2 NO2 + O2                                                               ', & ! index 235
     '     NO2 + MO2 --> MPN                                                                              ', & ! index 236
     '           MPN --> NO2 + MO2                                                                        ', & ! index 237
     '   ISOPNB + O3 --> 0.36 CO2 + 0.64 LOx + 0.21 PCO + 0.16 HCOOH + 0.21 MVKN + 0.42 PROPNN + 0.41 HNO3', & ! index 238
     '   ISOPND + O3 --> 0.63 CO2 + LOx + 0.09 EOH + 0.26 ETHLN + 0.06 GLYX + 0.38 PROPNN + 0.3 HNO3 + 0.2', & ! index 239
     '           HO2 --> O2                                                                               ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_8 = (/ &
     '           NO2 --> 0.5 LOx + 0.5 HNO2 + 0.5 HNO3                                                    ', & ! index 241
     '           NO3 --> LOx + HNO3                                                                       ', & ! index 242
     '          N2O5 --> LOx + 2 HNO3                                                                     ', & ! index 243
     '      DMS + OH --> CH2O + MO2 + SO2                                                                 ', & ! index 244
     '      DMS + OH --> 0.25 MSA + MO2 + 0.75 SO2                                                        ', & ! index 245
     '     DMS + NO3 --> LOx + HNO3 + CH2O + MO2 + SO2                                                    ', & ! index 246
     '      OH + SO2 --> SO4 + PSO4 + HO2                                                                 ', & ! index 247
     '       Br + O3 --> BrO + O2                                                                         ', & ! index 248
     '     BrO + HO2 --> HOBr + O2                                                                        ', & ! index 249
     '      Br + HO2 --> HBr + O2                                                                         ', & ! index 250
     '      HBr + OH --> Br + H2O                                                                         ', & ! index 251
     '         2 BrO --> 2 LOx + 2 Br + O2                                                                ', & ! index 252
     '         2 BrO --> 2 LOx + Br2 + O2                                                                 ', & ! index 253
     '      BrO + NO --> Br + NO2                                                                         ', & ! index 254
     '    BrNO3 + Br --> Br2 + NO3                                                                        ', & ! index 255
     '      Br2 + OH --> POx + HOBr + Br                                                                  ', & ! index 256
     '      BrO + OH --> LOx + Br + HO2                                                                   ', & ! index 257
     '      Br + NO3 --> BrO + NO2                                                                        ', & ! index 258
     '     CH2O + Br --> PCO + HBr + HO2 + CO                                                             ', & ! index 259
     '     ALD2 + Br --> HBr + MCO3                                                                       ', & ! index 260
     '     ACET + Br --> HBr + ATO2                                                                       ', & ! index 261
     '     C2H6 + Br --> HBr + ETO2                                                                       ', & ! index 262
     '     C3H8 + Br --> HBr + A3O2                                                                       ', & ! index 263
     '      Br + NO2 --> BrNO2                                                                            ', & ! index 264
     '     BrO + NO2 --> BrNO3                                                                            ', & ! index 265
     '    CHBr3 + OH --> 3 Br                                                                             ', & ! index 266
     '   CH2Br2 + OH --> 2 Br                                                                             ', & ! index 267
     '    CH3Br + OH --> Br                                                                               ', & ! index 268
     '         BrNO3 --> HOBr + HNO3                                                                      ', & ! index 269
     '          HOBr --> LOx + 0.5 Br2 + H2O                                                              ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_9 = (/ &
     '           HBr --> 0.5 Br2                                                                          ', & ! index 271
     '          HOBr --> LOx + 0.5 Br2 + H2O                                                              ', & ! index 272
     '           HBr --> 0.5 Br2                                                                          ', & ! index 273
     '      HC5 + OH --> HC5OO                                                                            ', & ! index 274
     '    HC5OO + NO --> POx + 0.09 PCO + 0.17 MOBA + 0.29 DHMOB + 0.216 GLYX + 0.234 GLYC + 0.234 MGLY + ', & ! index 275
     '    HC5OO + NO --> POx + HNO3                                                                       ', & ! index 276
     '   HC5OO + HO2 --> 0.1 IAP + 0.9 GLYC + 0.9 MGLY + 0.9 OH + 0.9 HO2                                 ', & ! index 277
     '   ISOPND + OH --> 0.9 LOx + 0.1 IEPOXD + 0.9 ISOPNDO2 + 0.1 NO2                                    ', & ! index 278
     '   ISOPNB + OH --> 0.9 LOx + 0.067 IEPOXA + 0.033 IEPOXB + 0.9 ISOPNBO2 + 0.1 NO2                   ', & ! index 279
     ' ISOPNDO2 + NO --> 1.394 POx + 0.27 DHDN + 0.057 HCOOH + 0.21 ETHLN + 0.075 MVKN + 0.3 PROPNN + 0.05', & ! index 280
     'ISOPNDO2 + HO2 --> POx + 0.5 ISNP + 0.2 ETHLN + 0.06 MVKN + 0.23 PROPNN + 0.01 MACRN + 0.23 GLYC + 0', & ! index 281
     ' ISOPNBO2 + NO --> 1.58 POx + 0.21 DHDN + 0.26 MVKN + 0.44 MACRN + 0.09 GLYC + 0.7 CH2O + 0.09 HAC +', & ! index 282
     'ISOPNBO2 + HO2 --> 1.01 POx + 0.51 ISNP + 0.16 MVKN + 0.28 MACRN + 0.06 GLYC + 0.44 CH2O + 0.06 HAC ', & ! index 283
     '     ISNP + OH --> 0.388 LOx + 0.193 ISOPNDO2 + 0.193 ISOPNBO2 + 0.612 R4N1 + 0.612 OH              ', & ! index 284
     '     MVKN + OH --> 0.35 PYAC + POx + 0.65 HCOOH + 0.65 MGLY + 0.35 CH2O + NO3                       ', & ! index 285
     '    MACRN + OH --> MACRNO2                                                                          ', & ! index 286
     '  MACRNO2 + NO --> 0.93 CO2 + 1.15 POx + 0.07 HCOOH + 0.08 ACTA + 0.07 MGLY + 0.08 CH2O + 0.85 HAC +', & ! index 287
     ' MACRNO2 + HO2 --> 0.93 CO2 + 0.15 POx + 0.07 HCOOH + 0.08 ACTA + 0.07 MGLY + 0.08 CH2O + 0.85 HAC +', & ! index 288
     ' MACRNO2 + NO2 --> LOx + PMNN                                                                       ', & ! index 289
     '          PMNN --> POx + MACRNO2 + NO2                                                              ', & ! index 290
     '    DHMOB + OH --> 1.5 PCO + 0.5 HAC + 0.5 MEK + HO2 + 1.5 CO                                       ', & ! index 291
     '    DIBOO + NO --> POx + 0.48 GLYX + 0.52 GLYC + 0.52 MGLY + 0.48 HAC + HO2 + NO2                   ', & ! index 292
     '    DIBOO + NO --> POx + HNO3                                                                       ', & ! index 293
     '   DIBOO + HO2 --> 0.85 R4P + 0.072 GLYX + 0.078 GLYC + 0.078 MGLY + 0.072 HAC + 0.15 OH + 0.15 HO2 ', & ! index 294
     '     MOBA + OH --> MOBAOO                                                                           ', & ! index 295
     '   MOBAOO + NO --> CO2 + POx + RCHO + HO2 + NO2                                                     ', & ! index 296
     '   MOBAOO + NO --> POx + HNO3                                                                       ', & ! index 297
     '  MOBAOO + HO2 --> 0.5 CO2 + 0.5 R4P + 0.5 RCHO + 0.5 OH + 0.5 HO2                                  ', & ! index 298
     '     MOBA + O3 --> CO2 + LOx + MEK + OH + HO2                                                       ', & ! index 299
     '    ETHLN + OH --> CO2 + CH2O + NO2                                                                 ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_10 = (/ &
     '   PROPNN + OH --> MGLY + NO2                                                                       ', & ! index 301
     '    CH2OO + NO --> POx + CH2O + NO2                                                                 ', & ! index 302
     '   CH2OO + NO2 --> POx + CH2O + NO3                                                                 ', & ! index 303
     '   CH2OO + SO2 --> SO4 + PSO4 + CH2O                                                                ', & ! index 304
     '   CH2OO + H2O --> H2O2 + CH2O                                                                      ', & ! index 305
     '   CH2OO + H2O --> HCOOH                                                                            ', & ! index 306
     '   MACROO + CO --> LCO + MACR                                                                       ', & ! index 307
     '   MACROO + NO --> POx + MACR + NO2                                                                 ', & ! index 308
     '  MACROO + NO2 --> POx + NO3 + MACR                                                                 ', & ! index 309
     '  MACROO + SO2 --> SO4 + PSO4 + MACR                                                                ', & ! index 310
     '  MACROO + H2O --> MRP                                                                              ', & ! index 311
     '  MACROO + H2O --> H2O2 + MACR                                                                      ', & ! index 312
     '    MVKOO + CO --> LCO + MVK                                                                        ', & ! index 313
     '    MVKOO + NO --> POx + MVK + NO2                                                                  ', & ! index 314
     '   MVKOO + NO2 --> POx + MVK + NO3                                                                  ', & ! index 315
     '   MVKOO + SO2 --> SO4 + PSO4 + MVK                                                                 ', & ! index 316
     '   MVKOO + H2O --> H2O2 + MVK                                                                       ', & ! index 317
     '   MGLYOO + CO --> LCO + MGLY                                                                       ', & ! index 318
     '   MGLYOO + NO --> POx + MGLY + NO2                                                                 ', & ! index 319
     '  MGLYOO + NO2 --> POx + MGLY + NO3                                                                 ', & ! index 320
     '  MGLYOO + SO2 --> SO4 + PSO4 + MGLY                                                                ', & ! index 321
     '  MGLYOO + H2O --> H2O2 + MGLY                                                                      ', & ! index 322
     '    MGLOO + CO --> LCO + MGLY                                                                       ', & ! index 323
     '    MGLOO + NO --> POx + MGLY + NO2                                                                 ', & ! index 324
     '   MGLOO + NO2 --> POx + MGLY + NO3                                                                 ', & ! index 325
     '   MGLOO + SO2 --> SO4 + PSO4 + MGLY                                                                ', & ! index 326
     '   MGLOO + H2O --> MO2 + MCO3                                                                       ', & ! index 327
     '   MGLOO + H2O --> H2O2 + MGLY                                                                      ', & ! index 328
     '  CH3CHOO + CO --> LCO + ALD2                                                                       ', & ! index 329
     '  CH3CHOO + NO --> POx + ALD2 + NO2                                                                 ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_11 = (/ &
     ' CH3CHOO + NO2 --> POx + ALD2 + NO3                                                                 ', & ! index 331
     ' CH3CHOO + SO2 --> SO4 + PSO4 + ALD2                                                                ', & ! index 332
     ' CH3CHOO + H2O --> H2O2 + ALD2                                                                      ', & ! index 333
     ' CH3CHOO + H2O --> ACTA                                                                             ', & ! index 334
     '     GAOO + CO --> LCO + GLYC                                                                       ', & ! index 335
     '     GAOO + NO --> POx + GLYC + NO2                                                                 ', & ! index 336
     '    GAOO + NO2 --> POx + GLYC + NO3                                                                 ', & ! index 337
     '    GAOO + SO2 --> SO4 + PSO4 + GLYC                                                                ', & ! index 338
     '    GAOO + H2O --> H2O2 + GLYC                                                                      ', & ! index 339
     '    GAOO + H2O --> HAC                                                                              ', & ! index 340
     '     BENZ + OH --> BRO2 + 0.252 GLYX + 1.92 CH2O + OH                                               ', & ! index 341
     '     TOLU + OH --> TRO2 + 0.26 GLYX + 0.215 MGLY + 1.92 CH2O + OH                                   ', & ! index 342
     '     XYLE + OH --> XRO2 + 0.268 GLYX + 0.463 MGLY + 1.92 CH2O + OH                                  ', & ! index 343
     '    XYLE + NO3 --> CO2 + 2 LOx                                                                      ', & ! index 344
     '          MONX --> 3 CH2O                                                                           ', & ! index 345
     '    BRO2 + HO2 --> LBRO2H                                                                           ', & ! index 346
     '     BRO2 + NO --> LBRO2N                                                                           ', & ! index 347
     '    TRO2 + HO2 --> LTRO2H                                                                           ', & ! index 348
     '     TRO2 + NO --> LTRO2N                                                                           ', & ! index 349
     '    XRO2 + HO2 --> LXRO2H                                                                           ', & ! index 350
     '     XRO2 + NO --> LXRO2N                                                                           ', & ! index 351
     '     MTPA + OH --> PIO2                                                                             ', & ! index 352
     '     PIO2 + NO --> 0.82 POx + 0.07 HCOOH + 0.12 MONITS + 0.11 ACET + 0.06 MONITU + 0.23 CH2O + 0.44 ', & ! index 353
     '    PIO2 + HO2 --> PIP                                                                              ', & ! index 354
     '    PIO2 + MO2 --> 0.25 ROH + 0.75 CH2O + 0.75 MEK + 0.75 RCHO + HO2 + 0.25 MOH                     ', & ! index 355
     '   PIO2 + MCO3 --> MEK + RCHO + 0.5 HO2 + 0.5 MO2 + RCOOH                                           ', & ! index 356
     '    PIO2 + NO3 --> LOx + MEK + RCHO + HO2 + NO2                                                     ', & ! index 357
     '     MTPA + O3 --> LOx + 0.14 PCO + 0.02 H2O2 + 0.62 KO2 + 0.53 MEK + 0.65 RCHO + 0.85 OH + 0.1 HO2 ', & ! index 358
     '    MTPA + NO3 --> 2 LOx + 0.9 OLND + 0.1 OLNN                                                      ', & ! index 359
     '     LIMO + OH --> LIMO2                                                                            ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_12 = (/ &
     '     LIMO + O3 --> LOx + 0.14 PCO + 0.02 H2O2 + 0.01 HCOOH + 0.16 ETO2 + 0.42 KO2 + 0.46 PRPE + 0.04', & ! index 361
     '    LIMO + NO3 --> 2 LOx + 0.5 OLND + 0.5 OLNN                                                      ', & ! index 362
     '    LIMO2 + NO --> 0.78 POx + 0.22 MONITU + 0.289 PRPE + 0.231 CH2O + 0.058 HAC + 0.289 MEK + 0.491 ', & ! index 363
     '   LIMO2 + HO2 --> PIP                                                                              ', & ! index 364
     '   LIMO2 + MO2 --> 0.25 ROH + 0.192 PRPE + 1.04 CH2O + HO2 + 0.308 MACR + 0.25 MOH                  ', & ! index 365
     '  LIMO2 + MCO3 --> 0.192 PRPE + 0.385 CH2O + 0.5 HO2 + 0.308 MACR + 0.5 MO2 + 0.5 RCOOH             ', & ! index 366
     '   LIMO2 + NO3 --> LOx + 0.385 PRPE + 0.385 CH2O + HO2 + 0.615 MACR + NO2                           ', & ! index 367
     '      PIP + OH --> 0.44 R4O2 + 0.41 MEK + 0.08 RCHO + 0.49 OH                                       ', & ! index 368
     '     OLNN + NO --> POx + MONITS + HO2 + NO2                                                         ', & ! index 369
     '     OLND + NO --> 2 POx + 0.287 CH2O + 0.464 MEK + 1.24 RCHO + 2 NO2                               ', & ! index 370
     '    OLNN + HO2 --> 0.7 MONITS + 0.3 MONITU                                                          ', & ! index 371
     '    OLND + HO2 --> 0.7 MONITS + 0.3 MONITU                                                          ', & ! index 372
     '    OLNN + MO2 --> 0.7 MONITS + 0.3 MONITU + CH2O + 2 HO2                                           ', & ! index 373
     '    OLND + MO2 --> 0.5 POx + 0.25 ROH + 0.35 MONITS + 0.15 MONITU + 0.965 CH2O + 0.348 MEK + 0.93 RC', & ! index 374
     '   OLNN + MCO3 --> 0.7 MONITS + 0.3 MONITU + HO2 + MO2                                              ', & ! index 375
     '   OLND + MCO3 --> POx + 0.287 CH2O + 0.464 MEK + 1.24 RCHO + NO2 + 0.5 MO2 + 0.5 RCOOH             ', & ! index 376
     '    OLNN + NO3 --> LOx + 0.7 MONITS + 0.3 MONITU + HO2 + NO2                                        ', & ! index 377
     '    OLND + NO3 --> 0.287 CH2O + 0.464 MEK + 1.24 RCHO + 2 NO2                                       ', & ! index 378
     '        2 OLNN --> 1.4 MONITS + 0.6 MONITU + HO2                                                    ', & ! index 379
     '   OLND + OLNN --> 0.5 POx + 1.05 MONITS + 0.45 MONITU + 0.202 CH2O + 0.149 MEK + 0.64 RCHO + 0.5 HO', & ! index 380
     '        2 OLND --> POx + 0.7 MONITS + 0.3 MONITU + 0.504 CH2O + 0.285 MEK + 1.21 RCHO + NO2         ', & ! index 381
     '   MONITS + OH --> HONIT                                                                            ', & ! index 382
     '   MONITU + OH --> HONIT                                                                            ', & ! index 383
     '   MONITU + O3 --> LOx + HONIT                                                                      ', & ! index 384
     '  MONITU + NO3 --> 2 LOx + HONIT                                                                    ', & ! index 385
     '  MONITS + NO3 --> 2 LOx + HONIT                                                                    ', & ! index 386
     '    HONIT + OH --> 2 POx + HAC + NO3                                                                ', & ! index 387
     '    HC187 + OH --> 0.5 PCO + 0.5 MGLY + CH2O + 0.5 HO2 + 0.5 CO + 0.5 MCO3                          ', & ! index 388
     '    HPALD + OH --> 0.085 CO2 + 0.55 PCO + 0.365 HPC52O2 + 0.085 GLYX + 0.55 MGLY + 0.55 CH2O + 0.635', & ! index 389
     '  DHPCARP + NO --> POx + GLYX + MGLY + OH + NO2                                                     ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_13 = (/ &
     '  HPC52O2 + NO --> POx + GLYX + MGLY + OH + NO2                                                     ', & ! index 391
     ' DHPCARP + HO2 --> RCOOH                                                                            ', & ! index 392
     ' HPC52O2 + HO2 --> RCOOH                                                                            ', & ! index 393
     '       DHPCARP --> PCO + OH + CO + RCOOH                                                            ', & ! index 394
     '       DHPCARP --> DHDC                                                                             ', & ! index 395
     '          GLYX --> SOAGX                                                                            ', & ! index 396
     '          MGLY --> SOAMG                                                                            ', & ! index 397
     '        IEPOXA --> SOAIE                                                                            ', & ! index 398
     '        IEPOXB --> SOAIE                                                                            ', & ! index 399
     '        IEPOXD --> SOAIE                                                                            ', & ! index 400
     '          IMAE --> SOAME                                                                            ', & ! index 401
     '          LVOC --> LVOCOA                                                                           ', & ! index 402
     '        ISN1OG --> ISN1OA                                                                           ', & ! index 403
     '        ISOPND --> LOx + IONITA                                                                     ', & ! index 404
     '        ISOPNB --> LOx + IONITA                                                                     ', & ! index 405
     '         MACRN --> LOx + IONITA                                                                     ', & ! index 406
     '          MVKN --> LOx + IONITA                                                                     ', & ! index 407
     '          R4N2 --> LOx + IONITA                                                                     ', & ! index 408
     '          DHDN --> IONITA                                                                           ', & ! index 409
     '        MONITS --> MONITA                                                                           ', & ! index 410
     '        MONITU --> MONITA                                                                           ', & ! index 411
     '         HONIT --> MONITA                                                                           ', & ! index 412
     '        IONITA --> INDIOL + POx + HNO3                                                              ', & ! index 413
     '        MONITA --> INDIOL + POx + HNO3                                                              ', & ! index 414
     '      NAP + OH --> NRO2 + OH                                                                        ', & ! index 415
     '    NRO2 + HO2 --> LNRO2H + HO2                                                                     ', & ! index 416
     '     NRO2 + NO --> LNRO2N + NO                                                                      ', & ! index 417
     '            O3 --> LOx + 2 OH                                                                       ', & ! index 418
     '            O3 --> LOx + OH + HO2                                                                   ', & ! index 419
     '           NO2 --> NO + O3                                                                          ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_14 = (/ &
     '          H2O2 --> 2 OH                                                                             ', & ! index 421
     '            MP --> CH2O + OH + HO2                                                                  ', & ! index 422
     '          CH2O --> PCO + 2 HO2 + CO                                                                 ', & ! index 423
     '          CH2O --> PCO + CO + H2                                                                    ', & ! index 424
     '          HNO3 --> OH + NO2                                                                         ', & ! index 425
     '          HNO2 --> OH + NO                                                                          ', & ! index 426
     '          HNO4 --> POx + OH + NO3                                                                   ', & ! index 427
     '          HNO4 --> HO2 + NO2                                                                        ', & ! index 428
     '           NO3 --> O3 + NO2                                                                         ', & ! index 429
     '           NO3 --> 2 LOx + NO + O2                                                                  ', & ! index 430
     '          N2O5 --> NO3 + NO2                                                                        ', & ! index 431
     '          ALD2 --> 0.88 PCO + HO2 + 0.88 CO + 0.88 MO2 + 0.12 MCO3                                  ', & ! index 432
     '          ALD2 --> PCO + CO + CH4                                                                   ', & ! index 433
     '           PAN --> 0.3 POx + 0.3 NO3 + 0.7 NO2 + 0.3 MO2 + 0.7 MCO3                                 ', & ! index 434
     '          RCHO --> PCO + ETO2 + HO2 + CO                                                            ', & ! index 435
     '          ACET --> MO2 + MCO3                                                                       ', & ! index 436
     '          ACET --> PCO + CO + 2 MO2                                                                 ', & ! index 437
     '           MEK --> 0.85 ETO2 + 0.15 RCO3 + 0.15 MO2 + 0.85 MCO3                                     ', & ! index 438
     '          GLYC --> PCO + 0.9 CH2O + 0.07 OH + 1.73 HO2 + CO + 0.1 MOH                               ', & ! index 439
     '          GLYX --> 2 PCO + 2 HO2 + 2 CO                                                             ', & ! index 440
     '          GLYX --> 2 PCO + 2 CO + H2                                                                ', & ! index 441
     '          GLYX --> PCO + CH2O + CO                                                                  ', & ! index 442
     '          MGLY --> PCO + HO2 + CO + MCO3                                                            ', & ! index 443
     '           MVK --> PCO + PRPE + CO                                                                  ', & ! index 444
     '           MVK --> PCO + CH2O + HO2 + CO + MCO3                                                     ', & ! index 445
     '           MVK --> RCO3 + MO2                                                                       ', & ! index 446
     '          MACR --> PCO + CH2O + HO2 + CO + MCO3                                                     ', & ! index 447
     '           HAC --> CH2O + HO2 + MCO3                                                                ', & ! index 448
     '          INPN --> RCHO + OH + HO2 + NO2                                                            ', & ! index 449
     '          PRPN --> RCHO + OH + HO2 + NO2                                                            ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_15 = (/ &
     '           ETP --> ALD2 + OH + HO2                                                                  ', & ! index 451
     '          RA3P --> RCHO + OH + HO2                                                                  ', & ! index 452
     '          RB3P --> ACET + OH + HO2                                                                  ', & ! index 453
     '           R4P --> RCHO + OH + HO2                                                                  ', & ! index 454
     '            PP --> CH2O + ALD2 + OH + HO2                                                           ', & ! index 455
     '            RP --> ALD2 + OH + HO2                                                                  ', & ! index 456
     '          RIPA --> 0.005 LVOC + 0.71 CH2O + 0.275 HC5 + 0.425 MVK + 0.985 OH + 0.985 HO2 + 0.285 MAC', & ! index 457
     '          RIPB --> 0.005 LVOC + 0.71 CH2O + 0.275 HC5 + 0.425 MVK + 0.985 OH + 0.985 HO2 + 0.285 MAC', & ! index 458
     '          RIPD --> 0.005 LVOC + 0.71 CH2O + 0.275 HC5 + 0.425 MVK + 0.985 OH + 0.985 HO2 + 0.285 MAC', & ! index 459
     '           IAP --> 0.67 PCO + 0.26 GLYC + 0.58 MGLY + 0.36 HAC + OH + HO2 + 0.67 CO + 0.19 H2       ', & ! index 460
     '          ISNP --> RCHO + OH + HO2 + NO2                                                            ', & ! index 461
     '           VRP --> 0.7 GLYC + 0.3 MGLY + 0.3 CH2O + OH + 0.3 HO2 + 0.7 MCO3                         ', & ! index 462
     '           MRP --> 0.5 PCO + 0.5 CH2O + HAC + OH + HO2 + 0.5 CO                                     ', & ! index 463
     '          MAOP --> CH2O + OH + MCO3                                                                 ', & ! index 464
     '          R4N2 --> 0.32 ACET + 0.05 A3O2 + 0.18 B3O2 + 0.32 ETO2 + 0.32 ALD2 + 0.19 MEK + 0.13 RCHO ', & ! index 465
     '           MAP --> OH + MO2                                                                         ', & ! index 466
     '         MACRN --> 0.5 PCO + MGLY + 0.5 CH2O + HAC + HO2 + 0.5 CO + NO2                             ', & ! index 467
     '          MVKN --> GLYC + NO2 + MCO3                                                                ', & ! index 468
     '        ISOPNB --> HC5 + HO2 + NO2                                                                  ', & ! index 469
     '           Br2 --> 2 Br                                                                             ', & ! index 470
     '           BrO --> Br + O3                                                                          ', & ! index 471
     '          HOBr --> LOx + Br + OH                                                                    ', & ! index 472
     '         BrNO3 --> Br + NO3                                                                         ', & ! index 473
     '         BrNO3 --> BrO + NO2                                                                        ', & ! index 474
     '         BrNO2 --> Br + NO2                                                                         ', & ! index 475
     '         CHBr3 --> 3 Br                                                                             ', & ! index 476
     '           MPN --> POx + CH2O + HO2 + NO3                                                           ', & ! index 477
     '           MPN --> NO2 + MO2                                                                        ', & ! index 478
     '        ISOPND --> HC5 + HO2 + NO2                                                                  ', & ! index 479
     '        PROPNN --> PCO + CH2O + CO + NO2 + MO2                                                      ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(10) :: EQN_NAMES_16 = (/ &
     '         ATOOH --> CH2O + OH + MCO3                                                                 ', & ! index 481
     '           PIP --> RCHO + OH + HO2                                                                  ', & ! index 482
     '          IPMN --> 0.4 CO2 + 1.4 POx + 0.6 IMAO3 + 0.4 CH2O + 0.4 NO3 + 0.6 NO2 + 0.4 MCO3          ', & ! index 483
     '         ETHLN --> PCO + CH2O + HO2 + CO + NO2                                                      ', & ! index 484
     '          DHDC --> GLYX + MGLY + 2 OH                                                               ', & ! index 485
     '         HPALD --> 1.89 PCO + 0.11 GLYC + 0.5 MGLY + 0.39 HAC + 2 OH + 0.89 HO2 + 1.89 CO + 0.11 MCO', & ! index 486
     '          ISN1 --> 0.25 GLYX + 0.5 GLYC + 0.25 MGLY + CH2O + 0.5 HAC + HO2 + NO2                    ', & ! index 487
     '        MONITS --> POx + MEK + NO2                                                                  ', & ! index 488
     '        MONITU --> POx + RCHO + NO2                                                                 ', & ! index 489
     '         HONIT --> POx + HAC + NO2                                                                  ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(490) :: EQN_NAMES = (/&
    EQN_NAMES_0, EQN_NAMES_1, EQN_NAMES_2, EQN_NAMES_3, EQN_NAMES_4, &
    EQN_NAMES_5, EQN_NAMES_6, EQN_NAMES_7, EQN_NAMES_8, EQN_NAMES_9, &
    EQN_NAMES_10, EQN_NAMES_11, EQN_NAMES_12, EQN_NAMES_13, EQN_NAMES_14, &
    EQN_NAMES_15, EQN_NAMES_16 /)

  CHARACTER(LEN=15), PARAMETER, DIMENSION(5) :: FAM_NAMES = (/ &
     'POx            ','LOx            ','PCO            ', & ! index 1 - 3
     'LCO            ','PSO4           ' /)

! INLINED global variables

! End INLINED global variables


END MODULE gckpp_Monitor
